### ISSUE TITLE
Outlook-style Replies

### ISSUE THREAD

**Issue by HubHubHubber** [jeevatkm/ReplyWithHeaderMozilla#1]
Looking forward to finally being able to easily get Outlook-style replies in Thunderbird and Postbox. Hopefully we'll be able to also finally get rid of the vertical nesting lines, too! ;)

**Comment by jeevatkm** [comment]
Sure, I will implement 'Handling blockquote (vertical lines)'. However moving into separate enhancement request #2

**Comment by HubHubHubber** [comment]
Hi Jeeva,

I just want to thank you again for taking the time to create this add-on for Thunderbird and Postbox. 

I really, really appreciate all your time and effort. 

Best,

Jake



On Apr 18, 2015, at 12:25 AM, Jeevanandam M. <notifications@github.com> wrote:

Sure, I will implement 'Handling blockquote (vertical lines)'. However moving into separate enhancement request #2

**Comment by jeevatkm** [comment]
It's done

**Comment by HubHubHubber** [comment]
Cool! Thank you. 

Would you like me to notify Postbox or wait until you have the version which removes the block quotes?


On May 20, 2015, at 2:51 PM, Jeevanandam M. <notifications@github.com> wrote:

It's done

**Comment by jeevatkm** [comment]
Add-on is ready to use, please explore prefs options and share your feedback.

I would like to sort out the issue you're facing in your machine then you can notify Postbox. Please not to wait for block quotes. That feature will be available in v1.1
