### ISSUE TITLE
Quoting message disable outlook reply styles

### ISSUE THREAD

**Issue by olaquetal** [jeevatkm/ReplyWithHeaderMozilla#100]
Hi,
I'm using Thunderbird 68.8.0 under linux.
ReplyWithHeaderMozilla works fine for me except if the option "Quote message" is enabled.
In that case, the header reverts to default thunderbird style.

Example (sorry it's in french) :
"Normal reply"

(start)

De : GitHub
Envoyé : jeudi 25 juin 2020 à 11:04 AM
Pour : olaquetal
Objet : A new security advisory on rack affects 2 of your repositories

xxxx
(end)

with quote option
(start)

Le 25/06/2020 à 11:04, GitHub a écrit :

xxxx
(end)

Thanks a lot for this nice plugin.

**Comment by jeevatkm** [comment]
@olaquetal It seems there is an error happening. Can you follow the below steps to collect logs and share them with me?

RWH add-on debug log:

* First enable the debug log via add-on preferences on About Tab - Check Enable debug mode
* Then open TB Error Console window by pressing 
   - on macOS `Shift + Command + J` 
   - on Windows/Linux `Shift + Ctrl + J`
* Now do Reply, Reply All or Forward behavior on the emails you have an issue
* Share all the debug line starts with `RWH` from the error console window and send to my email address `jeeva @ myjeeva.com`
