### ISSUE TITLE
Language translate to Trad-Chinese. and Vietnames, I can help.

### ISSUE THREAD

**Issue by kenxran** [jeevatkm/ReplyWithHeaderMozilla#101]
Dear Sir

Language translate to Trad-Chinese. and Vietnames, I can help. where is the language files? thanks !

**Comment by jeevatkm** [comment]
@it4u Sure, you can. Please refer to this PR #102 as an example.

**Comment by jeevatkm** [comment]
@kenneth-ran Any updates? Minimum you can help on providing values, I will create a PR.

**Comment by jeevatkm** [comment]
@kenxran Any updates on values?

**Comment by jeevatkm** [comment]
@kenxran I'm working on the WebExtension version of RWH. The branch is [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/tree/WebExtension). 

I require a sample string of the following in multiple languages for a `Plain Text` email.

**Reply**
```
On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
```

**Forward**
```
-------- Forwarded Message --------
Subject: Mozilla Add-on User Rating: ReplyWithHeader
Date: Sun, 28 Apr 2024 00:58:03 -0000
From: Thunderbird Add-ons <nobody@thunderbird.net>
To: jeeva@myjeeva.com
```

**Comment by jeevatkm** [comment]
@kenxran Added, please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
