### ISSUE TITLE
Brand new RWH v3.0.0 Mail Extension for TB future roadmap

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeaderMozilla#103]
In the #99 issue tracking, the short-term goal of adding TB 78 has been done and released to [ATN](https://addons.thunderbird.net/en-US/thunderbird/addon/replywithheader/). 

This issue is to track the new development of RWH v3.0.0 Mail Extention development.

**Comment by jeevatkm** [comment]
@frazar @ofa- @rostafiychuk I'm working on the WebExtension version of RWH. The branch is [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/tree/WebExtension). 

I require a sample string of the following in multiple languages for a `Plain Text` email.
```
On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
```

**Comment by p91paul** [comment]
For Italian:

Reply

```
Il 27/4/2024 alle 17:58, Thunderbird Add-ons ha scritto:
```

Forward

```
-------- Messaggio Inoltrato --------
Oggetto: Mozilla Add-on User Rating: ReplyWithHeader
Data: Domenica 28 Aprile 2024 00:58:03 -0000
Da: Thunderbird Add-ons <nobody@thunderbird.net>
A: jeeva@myjeeva.com

```

**Comment by jeevatkm** [comment]
Thanks, @p91paul, for your help.

**Comment by frazar** [comment]
Sorry, I can't provide with anything more than what you already have 😅

**Comment by ofa-** [comment]
Hi there @jeevatkm ! my Japanese contact is not reachable :-( I used goOgLe : 
![image](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/1472525/d6cd2f70-e95f-4577-83cb-e8fd8648d8d0)

Reply:

24/04/27 17:58に、 Thunderbirdのアドオン /// 書き込み: TOTO

**Comment by ofa-** [comment]
```
--------転送されたメッセージ--------
件名: Mozilla Add-on User
レーティング: ReplyWithHeader
日付: Sun, 28 Apr 2024 00:58:03 -0000
差出人: Thunderbird Add-ons
宛先: jeeva@myjeeva.com
```

**Comment by jeevatkm** [comment]
> Hi there @jeevatkm ! my Japanese contact is not reachable :-( I used goOgLe : ![image](https://private-user-images.githubusercontent.com/1472525/327136601-d6cd2f70-e95f-4577-83cb-e8fd8648d8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Nzg0NDEsIm5iZiI6MTcxNDU3ODE0MSwicGF0aCI6Ii8xNDcyNTI1LzMyNzEzNjYwMS1kNmNkMmY3MC1lOTVmLTQ1NzctODNjYi1lOGZkODY0OGQ4ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMTU0MjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU2YzRkOTBjZjJlMjk2ODYyMmZkNWJhYjc1NzQwZGI3ZDA3YmZhMDQ1M2ViYmJlZDJlMjAyNjc4Yjg3NTE4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dV8XnkHDghxtwT86W3p2u1-Em29o3GtYkex9KCcMhU0)
> 
> Reply:
> 
> 24/04/27 17:58に、 Thunderbirdのアドオン /// 書き込み: TOTO

Thanks, @ofa-. I require the translation provided by Thunderbird since I need to process plain text emails generated by Thunderbird.

**Comment by ofa-** [comment]
@jeevatkm then maybe go look into the TB source / i18n ?

**Comment by jeevatkm** [comment]
@ofa- Thanks for the message.  I did that exercise already, but I couldn't find a reference [here](https://github.com/mozilla/releases-comm-central). That's why I'm trying my luck with RWH users to collect data.

I'm planning to reach out to https://thunderbird.topicbox.com/groups/addons next. 

Just so you know, the above code reference you have shared belongs to the K-9 Android mobile app, not a TB desktop app.

**Comment by jeevatkm** [comment]
Hello RWH Users - 

I have created an RWH {Web|Mail}Extension version of the add-on. The v3 version is a complete rewrite from the ground up. Please try it and share feedback.
I have developed a significantly improved and capable RWH in v3. You will find it to be a significant enhancement to your workflow.

Download Link: https://docs.myjeeva.com/rwh-mozilla/replywithheader-v3.0.0.beta1.xpi

Cheers, Jeeva

**Comment by jeevatkm** [comment]
It requires minimum, TB v125 - https://ftp.mozilla.org/pub/thunderbird/releases/125.0/

**Comment by gabri25ele** [comment]
problem in "object"

old version
![old](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/33927879/f6db9f4a-2624-4c87-86e0-14665d7f9cd5)

more correct 
the "RE" is removed

new version
![new](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/33927879/ba14d485-76e2-45bd-b93c-4da81fa146e0)
the "RE" is present

;)

then I found that it's not good for **newsserver accounts**, ok they should be disabled. 
But could they have already been disabled at the start? 
Or is it even better to have an answer made specifically for this type of account?

**Comment by jeevatkm** [comment]
@gabri25ele I have validated it. The RWH v3 add-on does not add any prefix to the subject, e.g.,`Re:`; it must be TB v125 that is doing it. So, can you try TB v125 with the RWH v3 add-on?

I didn't understand the following three lines. What did you mean? 
> then I found that it's not good for newsserver accounts, ok they should be disabled.
> But could they have already been disabled at the start?
> Or is it even better to have an answer made specifically for this type of account?

**Comment by gabri25ele** [comment]
> @gabri25ele I have validated it. The RWH v3 add-on does not add any prefix to the subject, e.g.,`Re:`; it must be TB v125 that is doing it. So, can you try TB v125 with the RWH v3 add-on?

I tried 125 thunderbird, 
this image 
![329965973-ba14d485-76e2-45bd-b93c-4da81fa146e0](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/33927879/0760647e-c5b1-4333-a655-19caf3bbf246)
is from 125.

> 
> I didn't understand the following three lines. What did you mean?
> 
> > then I found that it's not good for newsserver accounts, ok they should be disabled.
> > But could they have already been disabled at the start?
> > Or is it even better to have an answer made specifically for this type of account?

Thunderbird is also a news reader, read newsgroup, so with newsserver, for example news.solani.org, the reply is not good, the quote message not work properly.

**Comment by jeevatkm** [comment]
@gabri25ele Did you mean the subject for `Re:` => `RE:` on the header attribution?

> Thunderbird is also a news reader, read newsgroup, so with newsserver, for example news.solani.org, the reply is not good, the quote message not work properly.

Now I understand, thanks. FYI, RWH always supported only Mail accounts.

**Comment by gabri25ele** [comment]
> @gabri25ele Did you mean the subject for `Re:` => `RE:` on the header attribution?
> 
> > Thunderbird is also a news reader, read newsgroup, so with newsserver, for example news.solani.org, the reply is not good, the quote message not work properly.
> 
> Now I understand, thanks. FYI, RWH always supported only Mail accounts.

yes, in fact just deactivate the accounts on the list
the problem is only with the object
https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106876869

**Comment by jeevatkm** [comment]
@gabri25ele That tells us that TB itself has an issue.

**Comment by jeevatkm** [comment]
Hello RWH Users -

Now `RWH v3.0.0.beta2` is ready! FYI, the v3 version is a complete rewrite from the ground up. Please try it and share feedback.
I have developed a significantly improved and capable RWH in v3. You will find it to be a significant enhancement to your workflow.

Download Link: https://github.com/jeevatkm/ReplyWithHeaderMozilla/releases/download/v3.0.0.beta2/replywithheader-v3.0.0.beta2.xpi

Cheers, Jeeva

**Comment by jeevatkm** [comment]
@gabri25ele I have investigated it; the `R` problem is coming from TB; the RWH addon doesn't do that. So please report it TB as a bug.

RWH only acts if it sees the `Re:` or `Fwd`; otherwise, nothing happens. 
Code reference: https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/f70e382a99aac20d88a8ab9640a864da71a6b5d0/modules/compose.mjs#L441-L449

**Comment by jeevatkm** [comment]
I have submitted the RWH v3.0.0 addon to ATN for review.
