### ISSUE TITLE
Translation to Dutch

### ISSUE THREAD

**Issue by BPower0036** [jeevatkm/ReplyWithHeaderMozilla#106]
The Outlook header style contains the english 'sent'
This is currently translated to Dutch with 'Datum'
However, it should be translated with 'Verzonden'
Can you change that?

**Comment by jmc8** [comment]
2 minutes at Translate.com confirmed this. My useless 2 cents.

**Comment by jeevatkm** [comment]
Closed by #111 , thanks @BPower0036
