### ISSUE TITLE
Transformation Re to RE and Fwd to FW not working in German

### ISSUE THREAD

**Issue by RalfKerkhoff** [jeevatkm/ReplyWithHeaderMozilla#109]
Hi,
the transformation (Misc TAB) from Re to RE and FWD to FW is not working with language set to German (thunderbird is german too).

Cheers
Ralf

**Comment by cnmicha** [comment]
@RalfKerkhoff Workaround: In `about:config`, set `mailnews.localizedRe` to `AW,Aw`. However, this has only an effect on new incoming email, not on messages that are already in your inbox or some other folder.

**Comment by RalfKerkhoff** [comment]
Hi,
it is already set to AW,Aw.

Just to make sure that I understand things in the right way:
If answering a mail the subject should be RE instead of Re and FW instead of Fwd - correct?

If I am right, that is not happening (tested with new mails).

Cheers
Ralf

**Comment by cnmicha** [comment]
I think your understanding is correct, however I don't know how well RWH plays together with the `mailnews.localizeRe` setting.

**Comment by jeevatkm** [comment]
@cnmicha  I'm sorry. To be honest, I have tested the RWH with only the English version TB build. I have not tested with any other **locale** version due to my time constraint.

**Comment by BPower0036** [comment]
The Re to RE doesn't happen in Dutch either, but FWD to FW does do it.

**Comment by jeevatkm** [comment]
@RalfKerkhoff @BPower0036 Do you mind providing sample email subject lines for me? It will help with debugging. Thanks.

**Comment by jeevatkm** [comment]
@RalfKerkhoff @BPower0036 @cnmicha if you see these two lines https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/a0271bcd14658903025e4e3b8d9d3e90a909baab/chrome/content/core.js#L647-L649

Code looks for English character and replaces it. So if I can get a values for language Dutch and German (possible all language supported by RWH), I will implement the logic to handle all languages Subject string.

**Comment by BPower0036** [comment]
The code looks correct.
The values in Duth are "RE:" and "FW".

**Comment by jeevatkm** [comment]
@BPower0036 So you have option enabled (under Misc tab) for subject prefix correction and its still not working for you, correct? can you share few screenshots for reply and forward behavior?

**Comment by BPower0036** [comment]
@jeevatkm I have tested it again, as my commit was from Oct 19, 2021.
But now it works as it should. So, n problem from my side anymore.
![afbeelding](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/80090789/417634b0-801b-420b-9eb0-e2784d9a29ca)
