### ISSUE TITLE
Problem with signature

### ISSUE THREAD

**Issue by mariobig** [jeevatkm/ReplyWithHeaderMozilla#11]
Your extension for Thunderbird is nice and practical. Unfortunately it removes my signature from frowarded mails. It would be usefull once it it is localized for other languages.

**Comment by jeevatkm** [comment]
Thanks, I will fix the signature issue in next release v1.4. 

For other languages, I will work on v1.5 release. Might need help on translation though for headers. Do you have any specific locale in your mind?

**Comment by mariobig** [comment]
Thanks for very quick reply. I thought about Polish headers.

**Comment by jeevatkm** [comment]
Okay, I will have a look on thunderbird internals for locale and let you know. Can you please create an issue for locale support, so we can track that separately?
```
pl_PL: "Polish (Poland)"
pl: "Polish"
```

**Comment by jeevatkm** [comment]
Signature issue is related with #13 too.

**Comment by jeevatkm** [comment]
I have addressed the Signature handling part. Can you please try v1.4-beta and share your feedback?

http://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v1.4-beta.xpi

**Comment by mariobig** [comment]
It works well now and the signature hasn't been removed. (checked on Mac OS X, not checked on Windows)

I would add one more option for this very useful add-on: either 12H or 24H time notation.

**Comment by jeevatkm** [comment]
Glad to hear. Please create an issue for 12H or 24H time notation.

**Comment by jeevatkm** [comment]
Created #15 for time format.

**Comment by jeevatkm** [comment]
@mariobig please take latest v1.4-beta version. It includes 12H or 24H notation too. Give a try and please let me know.

**Comment by mariobig** [comment]
I tested it on my MAC Book. It works well and 12H/24H notation is available. The only thing I would reconsider is the time precision. Do you really want to specify seconds? I haven't seen  such a precision in other mail clients.

**Comment by jeevatkm** [comment]
Thanks for sharing your view. I just a had a look on other mail clients. I will exclude seconds before the v1.4 release.

**Comment by mariobig** [comment]
Hello Jeevanandam,

Unfortunately you nice plugin to Thunderbird doesn't work properly after 
TB upgrade to version 45.1.0.
It doesn't attach header in case of mails forwarding.

Do you still work on plugin development? I would be very interested in 
its new version that fixes bugs.

Kind regards,

Mariusz Bielawski


wawaSOFT
	wawaSOFT INFO ,
mobile: +48 601 606 941
email: info@wawasoft.com
web: pl.wawasoft.com <http://pl.wawasoft.com>


Ta wiadomość została podpisana cyfrowo zgodnie ze standardem S/MIME. 
Tożsamość autora potwierdzona jest cyfrowym certyfikatem wystawionym 
przez zaufany urząd certyfikacji.
This message has been signed digitally in compliance with S/MIME 
standard. Identity of the author is confirmed by the digital certificate 
issued by trusted certification authority.
------------------------------------------------------------------------

------------------------------------------------------------------------
*From:* Jeevanandam M. <notifications@github.com>
*Sent:* Friday, Feb 12, 2016 20:26:15 GMT+0100
*To:* jeevatkm/ReplyWithHeaderMozilla 
<ReplyWithHeaderMozilla@noreply.github.com>
*Cc:* mariobig <info@wawasoft.com>
*Subject:* [ReplyWithHeaderMozilla] Problem with signature (#11)

**Comment by jeevatkm** [comment]
Yes, plugin is actively maintained. I will have a look on issue you have mentioned. 

Can you please create an new issue for TB v45.1.0 forward issue? if possible please add details whatever you can for tracing an issue.
