### ISSUE TITLE
Add Support for thunderbrid 91.0

### ISSUE THREAD

**Issue by jaisekjames** [jeevatkm/ReplyWithHeaderMozilla#110]
Currently replaywithheader is not working with Thunderbrid 91.0.

Pls add support for thunderbrid 91.0

**Comment by wikiaal** [comment]
Hi Jeeva, looking forward for a ReplyWithHeader version fitting to Mozilla Thunderbird 91.

Please, add support to this new version of Thunderbird.

Andrea

**Comment by jeevatkm** [comment]
@jaisekjames @wikiaal Thanks for reporting and creating an issue for TB 91 version. 

I will surely add support, first need to read and understand the changelog of TB 91 then I will implement it.

Thanks for your support.

**Comment by spodermenpls** [comment]
@jeevatkm I'm so glad that you're back, your absence since April worried me a bit. 😅

In case you didn't see it yet, this site should cover everything you need to know for transitioning RWH into an MailExtension "experiment": https://developer.thunderbird.net/add-ons/updating/tb91

**Comment by jeevatkm** [comment]
@spodermenpls Thank you, yes I'm reading that page. 
Yeah, it's due to my workplace became too busy for business reasons plus my personal end too.
Because of that, I couldn't finish #103 yet. At least I was glad RWH was in a working state but TB 91 release challenged "how come it's still working 🤣". 

First, I will make RWH work with TB 91+

_PS: Hoping things will get better by end of this year._

**Comment by jaisekjames** [comment]
> 
> 
> @jaisekjames @wikiaal Thanks for reporting and creating an issue for TB 91 version.
> 
> I will surely add support, first I need to read and understand the changelog of TB 91 then I will implement it.
> 
> Thanks for your support.

Thank you for looking into this. 

One minor bug facing is any attachment keyword below replay header also shows as warning[attachment missing banner].

**Comment by T200proX7** [comment]
Arch upgraded the Thunderbird Package to 91 and so i had to reinstall several addons (check for updates or simple update wasnt working). I removed all the old addons and installed the new one. All worked except the RWH. I install it but it seems to not get installed, as the button on the Addon Page "Install Addon" is still there and after reinstall it disappears from the addon list. 
No idea how to provide more (debug) informations.

**Comment by jobisoft** [comment]
I created a pull request with an updated version for TB91:
https://github.com/jeevatkm/ReplyWithHeaderMozilla/pull/112

Could you try if that version is working as intended in TB91?
[ReplyWithHeaderMozilla.zip](https://github.com/jeevatkm/ReplyWithHeaderMozilla/files/7142178/ReplyWithHeaderMozilla.zip)

**Comment by jobisoft** [comment]
Options are now in the add-on manager:
![grafik](https://user-images.githubusercontent.com/5830621/132821018-5bddc384-2c6b-4bf4-9fd8-5703b3a32f9e.png)

**Comment by wikiaal** [comment]
Hi Jeeva, many thanks for your support!!! For sure I will test a.s.a.p. the updated RWH for Thunderbird 91.x version and send feedback.

Andrea

**Comment by BackSpace54** [comment]
Hi,
thanks for what you have done atm.
RWH working again and first tests are ok (Thunderbird 91.1.0).

**Comment by wikiaal** [comment]
Hi Jeeva,
at a first test of new ReplyWithHeader version (2.4.0) with Thunderbird 91.1.0 (64 bit) installed as an upgrade from 78.14.0, it seems that everything works fine: ReplyWithHeader upgraded from previous (2.3.0) version has kept the settings, both SEND and FORWARD functions work correctly with the same layout (same number of blank lines, same font, same appearance of email header).

Andrea

**Comment by jobisoft** [comment]
One user reported here:

> One minor bug facing is any attachment keyword below replay header also shows as warning[attachment missing banner].

I have no idea what that means. Do you? Can you reproduce that? How?

**Comment by spodermenpls** [comment]
@jaisekjames Could you tell us how to reproduce the "attachment missing banner" warning you mentioned? I haven't upgraded to TB 91 yet, for the very reason that I wouldn't be able to use RWH (at least until now, I guess..).

@wikiaal Jeeva has the handle @jeevatkm, @jobisoft is a separate entity. 😉

**Comment by BackSpace54** [comment]
Hi again,
seem that previous RWH formatted the Header 'From' in outlook Extended like this _From: Name <email-address>_, in 2.4 it is formated like this _From: Name [mailto:email-address]_
So Thunderbird show two types of email in reply header one with [ ] and one with < >
Could you fix the Header 'From' in outlook Extended?

**Comment by jobisoft** [comment]
You sure? Even in the screenshot on the ATN page it is like so:
![grafik](https://user-images.githubusercontent.com/5830621/132843730-da537663-1cc5-4200-b10a-e3807e2f6d68.png)

**Comment by spodermenpls** [comment]
^ I can confirm that this formatting behaviour is already present under TB 78, this wasn't introduced by the porting of RWH to TB 91.

**Comment by BackSpace54** [comment]
Sorry, my bad...
The default option formated the email with < > so no issue.

**Comment by jaisekjames** [comment]
> 
> 
> @jaisekjames Could you tell us how to reproduce the "attachment missing banner" warning you mentioned? I haven't upgraded to TB 91 yet, for the very reason that I wouldn't be able to use RWH (at least until now, I guess..), therefore I can't check it myself right now.
> 
> @wikiaal Jeeva has the handle @jeevatkm, @jobisoft is a separate entity. 😉

I Upgraded to 91 version. Now tested with No issue found. 

"attachment missing banner" was in 78.x version. 

While forwarding, some attachment keyword is there, then it was popping. Now I tested, No issue with add-on.

**Comment by T200proX7** [comment]
> I created a pull request with an updated version for TB91:
> #112
> 
> Could you try if that version is working as intended in TB91?
> [ReplyWithHeaderMozilla.zip](https://github.com/jeevatkm/ReplyWithHeaderMozilla/files/7142178/ReplyWithHeaderMozilla.zip)

Hello. Thanks for fast answer. Yes this version is working well. The version on thunderbird addon page wasnt working.
Thank you.

**Comment by jobisoft** [comment]
Then we need @jaisekjames to answer, merge and release it.

**Comment by spodermenpls** [comment]
> Then we need @jaisekjames to answer, merge and release it.

@jobisoft I assume you mean @jeevatkm? 😅

**Comment by jobisoft** [comment]
Oh, yes, sorry.

**Comment by jeevatkm** [comment]
@jobisoft Hey John - it's been a while we had a conversation. Thank you so much for your PR.

I did the same exercise in the branch [for-tb-91](https://github.com/jeevatkm/ReplyWithHeaderMozilla/compare/for-tb-91?expand=1) and have been testing for few days. Also, I ran into one issue on **macOS** for the options screen, basically, the **selected tab label** does not show; spending few days figuring out why it is. I had a plan to reach on TB developer channel.

That's why I didn't create the RWH beta build yet.

<img width="935" alt="Screen Shot 2021-09-10 at 3 34 01 PM" src="https://user-images.githubusercontent.com/1175977/132925286-77eb2045-64f5-4e5c-aee0-45f87361eb53.png">

**Comment by 2BeeOrNot** [comment]
This also happens with RWH 2.3.0, Thunderbird 78.14.0 and macOS 11.5.2. I have not upgraded to Thunderbird 91 yet.

I fixed it using userChrome.css:

`/* Selected tab label not visible fix */`
`#rwhPane tabbox tabs tab[visuallyselected="true"]:not(:-moz-window-inactive) {`
`	/* is #fff in chrome://global/skin/tabbox.css:48 */`
`    color: unset !important; /**/`
`}`

![Options](https://user-images.githubusercontent.com/63317977/132935042-a0f7b072-2630-402b-909f-399fafc99b78.jpeg)

Thanks for RWH, it's a great add-on.

**Comment by jobisoft** [comment]
@jeevatkm Thank you for responding. I did not see the other branch, sorry. I would suggest pushing the updated version (yours or mine) to ATN as soon as possible because your *current* version claims compatibility with TB91 and breaks TB91 big time. So having this small issue on Mac, which we could fix later is a lot better, than dooming *all* your users by breaking their Thunderbird 91.

**Comment by jeevatkm** [comment]
@jobisoft Agreed, I will create a beta version and submit it on ATN, this week after the feedback I will create a release version.

**Comment by jeevatkm** [comment]
Dear RWH Users -

I have submitted the v2.4.0 add-on ATN. After approval, it will be available for one.

In the meantime, if you would like to download an add-on, you can use the below link.
Download Link: https://bit.ly/3hrdG5Q
Sha256: b3984cf7a06165a489c68d9f6e06c8a82f63643cf76ed2698a3f8e9a2b2855a8

Thanks for your support.

**Comment by wikiaal** [comment]
Cannot install RWH 2.4.0 on my TB 91.1.0 because I receive a message that the "object is damaged".

Andrea

**Comment by jeevatkm** [comment]
@wikiaal - can you please try this link? - https://docs.myjeeva.com/rwh-mozilla/replywithheader-v2.4.0.xpi
