### ISSUE TITLE
More explanatory descriptions/examples

### ISSUE THREAD

**Issue by spodermenpls** [jeevatkm/ReplyWithHeaderMozilla#114]
Inside the general settings, the lack of a preview example after the 1st "Default" (in this case `From: Name <email-address>`) leaves the user a bit in the dark about what to expect from the first standard setting, maybe you can add an example there too, like you did for the other settings. Same goes for the "don't include plain text header prefix" option in the Misc column, it was unclear even to me that this was supposed to be the technical term for `----Forwarded Message----` type of separator lines, that get removed with this checkbox being ticked.

_Originally posted by @spodermenpls in https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/110#issuecomment-916823394_

**Comment by jeevatkm** [comment]
@spodermenpls Makes sense. Will try to add additional info for the options.

**Comment by jeevatkm** [comment]
I'm going to close this one. Gradually, I will improve it. Thanks.
