### ISSUE TITLE
Forwarding emails downloads remote content although TB was configured to block remote content

### ISSUE THREAD

**Issue by cnmicha** [jeevatkm/ReplyWithHeaderMozilla#116]
I set up a fresh installation of Thunderbird with no addons.

Thunderbird's default setting when receiving HTML messages with remote images is blocking the download of the remote content and displaying a warning message ("To protect your privacy, Thunderbird has blocked remote content in this message").
When forwarding that email, remote content is not downloaded (as I expected, because I have not clicked the "Show remote content in this message" button next to the warning message).

Now I installed the RWH addon. When viewing the message, the warning message still appears. But when clicking TB's "Forward" button, it starts downloading remote images inside the composer window...

I think this should not be the case.

**Comment by nitemn** [comment]
Go into Thunderbird Preferences and under Privacy and Security Section check the checkbox that says:  Allow Remote content in Messages.  That will resolve your issue.

**Comment by cnmicha** [comment]
I do not want to allow remote content in messages and I think TB is configured like that.
But if the RWH addon is installed, this TB setting seems to be ignored in the composer window.

**Comment by jeevatkm** [comment]
@cnmicha Thanks for reaching out. As far as I know, RWH do not do any processing as you mentioned. I will have to analyzed. In the meantime, do you mind sharing the TB setting details around this?

**Comment by jeevatkm** [comment]
@cnmicha Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608, can you try it?

**Comment by jeevatkm** [comment]
Now, RWH v3.0.0.beta2 is ready! Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2114025131
