### ISSUE TITLE
Possible to use "Paragraph" instead of "Body Text" as paragraph format?

### ISSUE THREAD

**Issue by x3rAx** [jeevatkm/ReplyWithHeaderMozilla#117]
Hi,

great extension! However I noticed that the paragraph format is "Body Text" when when replying while the extension is active. Without the extension it is "Paragraph".

The main difference (at least for me) is that with "Paragraph" you hit Enter only once and a half-line-height gap is produced between paragraphs. With "Body Text" however, there is no such gap and you have to hit Enter twice to produce a paragraph. The spacing between the paragraphs is then of course not only a half-line-height gap but a fill-line-height gap.

Usually, when I compose a new mail, it is "Paragraph" and when I reply without the extension active, it is also "Paragraph". But with the extension enabled, I get "Paragraph" for new mails and "Body Text" when replying.

Is it possible to change this behavior?

**Comment by jeevatkm** [comment]
@x3rAx Do you mind providing HTML email content? it will help with debugging. thanks.

**Comment by jeevatkm** [comment]
@x3rAx Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
