### ISSUE TITLE
Incompatible with Thunderbird 102

### ISSUE THREAD

**Issue by jaisekjames** [jeevatkm/ReplyWithHeaderMozilla#118]
Please make compatible with TB 102.
Release candidate 1 (RC1) is available at https://archive.mozilla.org/pub/thunderbird/candidates/102.0-candidates/build1/

**Comment by maxmichels** [comment]
@jaisekjames i found a solution: you can manually edit the maximum version and it will work again. The code itself is fully compatible.
https://kb.mozillazine.org/Editing_an_add-on_to_change_its_compatibility

You must change the max version to 102.* and it works again :-)

**Comment by nitemn** [comment]
This is great but I can not find the .rdf install file in the .XPI archive?  Can you please let me know which file you changed to make this work?
Thank you

**Comment by ynjo** [comment]
You can change manifest.json file instead

**Comment by maxmichels** [comment]
Exactly as @ynjo said. The version has to be changed in the manifest.json

**Comment by spodermenpls** [comment]
> You must change the max version to 102.* and it works again :-)

@jeevatkm

**Comment by Fredrik-69** [comment]
Just a small tip: if you use 7-zip you don't even need to unpack/repack the XPI file. You can open the existing file directly with 7-zip, make modifications via ALT+ENTER, open manifest.json in for example Notepad++, save the file and let 7-zip update the archive.
C:\Users\<name>\AppData\Roaming\Thunderbird\Profiles\<profile>\extensions\replywithheader@myjeeva.com.xpi

**Comment by jeevatkm** [comment]
Hello @jaisekjames and everyone - Thanks I will start looking into it and make the required updates.

**Comment by maxmichels** [comment]
@jeevatkm do you know until when you will have fixed it? 😄

**Comment by wikiaal** [comment]
The suggested https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/118 workaround works!!!

I changed "strict_max_version": "91.*" to "strict_max_version": "102.*" in manifest.json (in [replywithheader@myjeeva.com.xpi](mailto:replywithheader@myjeeva.com.xpi)) and ReplyWithHeader v2.4.0 works with Thunerbird v102.

I found it in this path (it refers to a MS Windows 11 installation):

C:\Users\USERNAME\AppData\Roaming\Thunderbird\Profiles\75y65lmn.default-release\extensions\[replywithheader@myjeeva.com.xpi](mailto:replywithheader@myjeeva.com.xpi)

You can OPEN [replywithheader@myjeeva.com.xpi](mailto:replywithheader@myjeeva.com.xpi) with 7-Zip

Select manifest.json in the root folder and EDIT (F4) it directly within 7-Zip

Change

"strict_max_version": "91.*" to "strict_max_version": "102.*"

SAVE and CONFIRM that you "want to update it in the archive"

DONE and ReplyWithHeader v2.4.0 works with Thunerbird v102

Andrea

**Comment by jeevatkm** [comment]
Hello Everyone - My apologies for the delay, due to personal reasons, it got delayed.  This time it's minor update #120  (version no and ACM support script update).

I have submitted `v2.5.0` on ACM for review, in the meantime, if you need a release version, you can grab it from https://bit.ly/3PGuMeI

Thanks for your patience and support, I appreciate it!

Cheers, Jeeva
