### ISSUE TITLE
Thunderbird v102 and ReplyWithHeader

### ISSUE THREAD

**Issue by wikiaal** [jeevatkm/ReplyWithHeaderMozilla#119]
Hi Jeeva,
Mozilla released Thunderbird v102. Do you plan to support this new version with your ReplyWithHeader extension?

Kind regards
Andrea

**Comment by ThePirat91** [comment]
+1
It would be very appreciated...
Thanks

**Comment by Fredrik-69** [comment]
In the meanwhile just do as suggested in the duplicate issue #118.

**Comment by wikiaal** [comment]
The suggested workaround works!!!

I changed the max version to "strict_max_version": "102.*" in manifest.json (in replywithheader@myjeeva.com.xpi) and ReplyWithHeader v2.4.0 works with Thunerbird v102.

I found it in this path:

C:\Users\<uresname>\AppData\Roaming\Thunderbird\Profiles\75y65lmn.default-release\extensions\replywithheader@myjeeva.com.xpi

You can OPEN replywithheader@myjeeva.com.xpi with 7-Zip

Select manifest.json in the root and EDIT (F4) it directly within 7-Zip

Change "strict_max_version": "91.*" to "strict_max_version": "102.*"

SAVE and CONFIRM that you "want to update it in the archive"

DONE

**Comment by jeevatkm** [comment]
Hello @wikiaal and everyone - Thanks, I will start looking into it and make the required updates.

**Comment by jeevatkm** [comment]
Hello Everyone - My apologies for the delay, due to personal reasons, it got delayed.  This time it's minor update #120  (version no and ACM support script update).

I have submitted `v2.5.0` on ACM for review, in the meantime, if you need a release version, you can grab it from https://bit.ly/3PGuMeI

Thanks for your patience and support, I appreciate it!

Cheers, Jeeva

**Comment by Fredrik-69** [comment]
Superb! Well done.
If you want you can delete 'version_name' from manifest.json since it is not supported by Mozilla anyway. It only generates a warning in the developer console.
Ref. [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version_name](url)

**Comment by dpate71** [comment]
@jeevatkm  You may update Compatibility Matrix on https://myjeeva.com/replywithheader-mozilla to include v2.5.0.

**Comment by jeevatkm** [comment]
@Fredrik-69 Thanks for pointing out the deprecated config info, I will take care in the next update. 

@dpate71 Compatibility matrix updated, thanks!
