### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by mariobig** [jeevatkm/ReplyWithHeaderMozilla#12]
ReplyWithHeaderMozilla would require localization for other languages, specifically for Polish pl_PL.

**Comment by princemichi** [comment]
Hello,
i would recommend a German translation. 
Please contact me if you need a translation!

**Comment by jeevatkm** [comment]
@princemichi Thank you for your interest. To bring localization feature, first we need to enable add-on to adapt to localization. Then we can easily any language into it.

Will work on when I get a sufficient time. Thanks again.

**Comment by ofa-** [comment]
See e.g. #31 for basic i18n / translation proposal.

**Comment by jeevatkm** [comment]
@mariobig @princemichi Hope you're doing well. @ofa- have contributed i18n support for header labels.  Can you please provide translation for following?

```
From:
To:
Cc:
Subject:
Date:
Sent:

Forwarded Message
Original Message
```

For reference @ofa- added `fr` locale values https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/master/content/rwh.js#L926-L959

**Comment by jeevatkm** [comment]
@ofa- Its done, please branch out fresh from master for your work going forward.

**Comment by ofa-** [comment]
@jeevatkm ok thanks.  I had this drop-down at the top right corner first, then realised it was more related to the headers labels lang - and it is - so I decided to put it there instead;  your call anyway.

Next step for me will [probably] be to provide a way select the headers' language based on the sending account email - I have multiple accounts, some in French, some in English.

An alternative method for auto-selecting lang would be to use the destination email, but this not my priority.

**Comment by ofa-** [comment]
Full headers localization requires date [and time] i18n support.
These last bits are addressed by PR #41

**Comment by ofa-** [comment]
include #45

**Comment by ofa-** [comment]
include #42

**Comment by ofa-** [comment]
include #41

**Comment by ofa-** [comment]
@jeevatkm I suggest you edit your comment https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/12#issuecomment-364220581
to reference https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/master/content/rwh-i18n.js

**Comment by ofa-** [comment]
(and I'll delete above comments, to cleanup the issue log)

**Comment by jeevatkm** [comment]
@mariobig @princemichi -  @ofa- Have contributed wonderful locale support, kudos. 

To be released with `v2.0`.

**Comment by ofa-** [comment]
Hey @jeevatkm, FYI, I think I saw @princemichi ask __when__ v2.0 was going to be relased.

**Comment by ofa-** [comment]
@jeevatkm you want to EDIT your comment here https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/12#issuecomment-364220581

The link you provide is no longer relevant :-)  I suggest you use that instead:

=> https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/master/content/rwh-i18n.js
