### ISSUE TITLE
When replying to message threads, a new line is not inserted

### ISSUE THREAD

**Issue by vincejv** [jeevatkm/ReplyWithHeaderMozilla#121]
When this addon is active, when replying to message threads, a new line is not inserted, however when starting a new email from scratch a new line is inserted.
Might be related to #75, I think new Thunderbird versions compensate for the bug mentioned in #75, my suggestion is to have a setting for this or to detect the thunderbird version.

See the screenshot below with Thunderbird 102.1.2
### New Email:
![image](https://user-images.githubusercontent.com/1276544/184068519-d51bee7a-cdfc-424b-8968-53aa7b5e7a52.png)

### Reply/Forward:
![image](https://user-images.githubusercontent.com/1276544/184068607-9a88f88d-e8c5-461f-aaa5-fd6cd0fdabc2.png)

**Comment by Unambiguous** [comment]
I confirm that a new line is missing at the beginning of the reply. However, this issue is slightly broader. If using plain text signatures, Thunderbird uses a specific format and style (namely "Preformat") for the signature. When I then add a new line manually, the new line inherits the text style from the signature which is different from a default text style.

![image](https://user-images.githubusercontent.com/5543209/189071686-2fd5182b-1f98-45b5-8ce3-fc5eb77978b8.png)

**Comment by netjeff** [comment]
I'm seeing similar symptoms.

**Comment by Thaledwyn** [comment]
This happened to me after TB update from 91.x to 102.x

BUT it only appears on **forwarding** emails.
When replying, everything is ok.

**Comment by jpl75** [comment]
I have the issue on reply also.

Some more details on the issue.

My Thunderbird settings :
 

>   -  Automaticaly quote the original message when replying : checked
>     - and place my signature below my reply (above the quote)
>     - Include signature for replies : checked
>     - Include signature for forward : checked

When I reply to a mail **without ReplyWithHeader**, the beginning of the mail is :

   

>  <!DOCTYPE html>
>     <html>
>       <head>
>         <meta http-equiv="Content-Type" content="text/html; charset=">
>       </head>
>       <body>
>         <p><br>
>         </p>
>         <div class="moz-signature">

When I reply to a mail **with ReplyWithHeader**, the beginning of the mail is :

>     <!DOCTYPE html>
>     <html>
>       <head>
>         <meta http-equiv="Content-Type" content="text/html; charset=">
>       </head>
>       <body>
>         <div class="moz-signature">

So apparenly the line above the signature is removed by ReplyWithHeader. Note : I made the test with all other extensions removed.

Thanks in advance for the resolution.

**Comment by franck-tomek** [comment]
Same problem here, on all cases (reply / forward).

**Comment by jpl75** [comment]
> When this addon is active, when replying to message threads, a new line is not inserted, however when starting a new email from scratch a new line is inserted. Might be related to #75, I think new Thunderbird versions compensate for the bug mentioned in #75, my suggestion is to have a setting for this or to detect the thunderbird version.


I tried to undo the changes done for #75. It corrected the issue for replies, not for forward.

**Comment by jeevatkm** [comment]
Thanks for the discussion. Handling signature part is gets tricky. I will try to reproduce and fix, when I need help I will reach out here.

**Comment by jeevatkm** [comment]
@vincejv I have created a v2.7.0-beta build; please try it out and share feedback.
https://docs.myjeeva.com/rwh-mozilla/replywithheader-v2.7.0-beta.xpi

**Comment by Unambiguous** [comment]
I have retested the issue on Thunderbird 115.3.1 (64-bit) with v2.7.0-beta.
The issue still remains. There is a missing newline when replying and using signatures at the same time.

**Comment by anttiisoaho** [comment]
Thunderbird settings -> Composition -> HTML Style
Uncheck "Use Paragraph format instead of Body Text by default"

**Comment by jeevatkm** [comment]
@Unambiguous newline issue sorted out screenshots for you to take a look at.

**Reply**
<img width="860" alt="Screenshot 2023-10-11 at 7 44 05 PM" src="https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/1175977/9334f6a8-5102-458e-b512-3610ecf529d4">


**Forward**
<img width="856" alt="Screenshot 2023-10-11 at 7 44 53 PM" src="https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/1175977/1eec64c0-6462-40ea-b18e-98610cd9230b">

**Comment by Unambiguous** [comment]
I confirm that the newline works correctly now. It works regardless on the settings mentioned in https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/121#issuecomment-1757989505.
It seems that I had to restart Thunderbird a few times in order for the changes to take effect.

Thank you, @jeevatkm.
