### ISSUE TITLE
EWS automatic signature misplaced

### ISSUE THREAD

**Issue by luizdl** [jeevatkm/ReplyWithHeaderMozilla#122]
EWS automatic signature fails to identify mail separator, and then puts the signature on the end of the e-mail, or just after the signature of the person I'm replying.

I can avoid this inserting several underscore at the end of my message, for exemple _______________________________________.
Doing this, EWS identify it as the mail separator. But when using Outlook our Outlook Web, it puts a different separator that is also correctly identitied by EWS, I'm not sure if its a HTML tag, or a class or anything else.

**Comment by jeevatkm** [comment]
@luizdl Thanks for reporting it.  
This is very hard to tackle with original email HTML during a development. Do you mind sending the non-sensitive email content as an attachment or forward to my email address? 
Then I will use the provided content for debugging and development to fix the issue.

**Comment by jeevatkm** [comment]
@luizdl Thanks for getting back. 

> The issue now is that ReplyWithHeader line bar split up my e-mail content from my signature.

Do you mind sharing a screenshot?

**Comment by luizdl** [comment]
Hi, follow a screenshot with some blurred parts from my last test.
Currently I simply delete the line bar before to send e-mail

![image](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/53983517/53c7fb71-b064-4c17-9722-ca3e0aa27052)

**Comment by jeevatkm** [comment]
@luizdl Thanks for sharing the screenshot. Recently, I did work on a new line issue above the signature. Do you mind trying this beta version?
https://docs.myjeeva.com/rwh-mozilla/replywithheader-v2.7.0-beta.xpi

**Comment by luizdl** [comment]
Same issue.

Actually the Signature does not exist before to click "send" button, in my case it's the mail server that places the signature while sending the e-mail, I can only know where the signature was placed if I send it to myself.

There is something different in the line bar that Microsoft Outlook put that identifies the end of message, I don't know what exactly does it.
But as currently the mail server is detecting correctly the mail header to put the signature before it, it shoul'd be enough if there's an option in configuration to choose to not put the line bar. Currently the configuration only allows tho choose the line size with the minimum of 1px.
![image](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/53983517/26e6ff45-e400-4627-ab9f-0455dcd6edb8)

**Comment by jeevatkm** [comment]
@luizdl can you please try v3 beta1? https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608

**Comment by jeevatkm** [comment]
@luizdl Now, RWH v3.0.0.beta2 is ready! Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2114025131
