### ISSUE TITLE
Per-account reply

### ISSUE THREAD

**Issue by pztrn** [jeevatkm/ReplyWithHeaderMozilla#123]
I have:

* Personal account which participates in mailing lists on which top posting considered harmful.
* Work account where correspondents uses top posting (just because 99% of them using Outlook).

It will be great if I'll be able to select account in settings for which ReplyWithHeaders extension is active.

**Comment by jeevatkm** [comment]
@pztrn Thanks for the suggestion. The RWH need to be rewritten with latest TB plugin/extension model. The current version is kind of hybrid version. I will consider this input for RWH v3.0.0 .

**Comment by jeevatkm** [comment]
@pztrn I'm not sure, if you're still using TB and RWH. I thought to inform you. Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
