### ISSUE TITLE
Error in non-English (Dutch) language

### ISSUE THREAD

**Issue by ArieVerhagen** [jeevatkm/ReplyWithHeaderMozilla#125]
After selection of Dutch as language in the extension's preferences, the header line above a forwarded message (inline) is strange and wrong. The text between the dashes reads "het volgende geschreven" (lit: "the following written"). I couln't find if/how this can be corrected.

**Comment by jeevatkm** [comment]
@ArieVerhagen The header translation is coming from https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/master/chrome/content/i18n.js can you please review for Dutch?

**Comment by ArieVerhagen** [comment]
Thanks. Sure. Everything looks fine, except line 169. That one should read:
"nl": "Doorgestuurd bericht"

**Comment by jeevatkm** [comment]
Thanks, right now I'm working on to make v2.6.0 release for TB 115.x. I will include this update.
