### ISSUE TITLE
Thunderbird 115 support

### ISSUE THREAD

**Issue by ynjo** [jeevatkm/ReplyWithHeaderMozilla#129]
Hello,

any chance to have a new version of ReplyWithHeader to support this new version of Thunderbird?

Thanks a lot!

**Comment by jobisoft** [comment]
Here is a version based on PullRequest #130: 

[ReplyWithHeaderMozilla.zip](https://github.com/jeevatkm/ReplyWithHeaderMozilla/files/12152839/ReplyWithHeaderMozilla.zip)

You can drag and drop the link into Thunderbird's add-on manger, or download the file and install it through the gear icon in Thunderbird's add-on manager.

**Comment by ynjo** [comment]
It works correctly, thank you very much!

**Comment by jobisoft** [comment]
I think as long as the maintainer of this add-on has not accepted the pull request provided by the Thunderbird Team, or has released a version for TB115, this issues should remain open :-)

**Comment by ynjo** [comment]
and you are right, you solved my problem, but let's wait for an official release.
Thanks again

**Comment by jeevatkm** [comment]
@ynjo

I have released v2.6.0 version for TB 115 support and few improvements too.
Also I have submitted the v2.6.0 addon for review on ATN.

Releases Notes: https://github.com/jeevatkm/ReplyWithHeaderMozilla/releases/tag/v2.6.0

**Comment by ynjo** [comment]
Thank you very much!
