### ISSUE TITLE
When forwarding emails headers do not attach

### ISSUE THREAD

**Issue by mswildma77** [jeevatkm/ReplyWithHeaderMozilla#131]
When the add-on is enabled and you reply or forward a message with full headers, for example to report SPAM emails to a filter, it still only gives shortened normal headers. Is there a way to have it include the headers as shown if full headers are displayed in the message?

**Comment by jeevatkm** [comment]
@mswildma77 Do you mean including all the message header(s) in the visible part of the email? 
Typically when SPAM report email gets processed, it goes by original email headers not the visible one. And RWH only does visible one, it does not touch the original headers. Please let me know, did I understand it correctly?

**Comment by mswildma77** [comment]
Yes I am talking about the Full Original Header.  Normally I am on view "Normal" for the headers but when I have to forward a message to my SPAM filter to learn I need to change the header viewing to "All" so the entire header string is visible.  After I do that and click forward with the add-on enabled it does not copy the full header into the forwarded message unless I turn off the add-on.

**Comment by jeevatkm** [comment]
@mswildma77 I'm able to replicate the issue. I will tackle it.

**Comment by mswildma77** [comment]
Thanks
-----------
Michael S. Wildman, AIA, LEED AP BD+C
WILDMAN ARCHITECTURE PLLC
158 Manhattan Street
Staten Island, NY 10307
t: 917-626-7887
f: 917-626-7887
***@***.***
www.michaelwildman.com

**Comment by jeevatkm** [comment]
@mswildma77 Feature is implemented, please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2114025131
