### ISSUE TITLE
New line missing when forwarding message (signature included)

### ISSUE THREAD

**Issue by jcacqua** [jeevatkm/ReplyWithHeaderMozilla#134]
I'm on version 2.5.0 on v102.15.0
It is impossible to write before signature when forwarding a mail because a new line is missing

**Comment by jeevatkm** [comment]
@jcacqua Do you mind sharing a screenshot?

**Comment by crazypeace** [comment]
I guess this guy meet the same problem of mine.
https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/136

**Comment by jcacqua** [comment]
> @jcacqua Do you mind sharing a screenshot?

![image](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/58211101/0ca10def-fa56-4338-ac1f-c8f24732d673)

**Comment by jeevatkm** [comment]
Thanks, @jcacqua, for sharing the screenshot.

**Comment by jeevatkm** [comment]
@jcacqua I have created a v2.7.0-beta build; please try it out and share feedback.
https://docs.myjeeva.com/rwh-mozilla/replywithheader-v2.7.0-beta.xpi

**Comment by jcacqua** [comment]
it says "Not compatible with 102.15.1"

**Comment by jeevatkm** [comment]
@jcacqua good to hear it's working fine with TB 115.*

**Comment by IgitBuh** [comment]
Could you please clarify, when will this fix be officially available?
It's actually not just a minor inconvenience, because this missing empty line also prevents the spell checking from working. See #142 

While I'm here: Thank you very much for this addon and your continuous work on it!
I absolutely don't understand why this option is not part of Thunderbird by default.

**Comment by IgitBuh** [comment]
> @jcacqua I have created a v2.7.0-beta build; please try it out and share feedback. https://docs.myjeeva.com/rwh-mozilla/replywithheader-v2.7.0-beta.xpi

I have now manually installed the v2.7.0-beta version and can confirm that it solves the problem! After restarting Thunderbird, replying or forwarding emails added the required empty line at the top. As a result, spell-check works again.
Thank you, looking forward to the official release!
