### ISSUE TITLE
The sign is at the top

### ISSUE THREAD

**Issue by crazypeace** [jeevatkm/ReplyWithHeaderMozilla#136]
The sign is at the top

Thunderbird 115.2.2（64 位）

ReplyWithHeader 
版本
2.6.0
上次更新
2023年9月19日

![图片](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/665889/6bb404b4-8b93-403e-ba16-3a1df12ca266)

**Comment by jeevatkm** [comment]
@crazypeace Thanks for reporting it.

**Comment by jeevatkm** [comment]
@crazypeace I have created a v2.7.0-beta build; please try it out and share feedback.
https://docs.myjeeva.com/rwh-mozilla/replywithheader-v2.7.0-beta.xpi
