### ISSUE TITLE
Sent header in Dutch contains a word, which should be omitted

### ISSUE THREAD

**Issue by BPower0036** [jeevatkm/ReplyWithHeaderMozilla#138]
It is not a big deal, the Duth 'om' in the date should be omitted when outlook extended is activated.
![afbeelding](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/80090789/a997f7a8-5f91-4a6d-aa1c-5c803c634efa)
![afbeelding](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/80090789/67efa6b6-5145-4029-aed3-ebc6deb4f25b)

See original Outlook: 
![afbeelding](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/80090789/c20904d2-3c28-4dfc-ad96-53a240844b97)

**Comment by jeevatkm** [comment]
@BPower0036 I have looked at it. I'm not inserting the word 'om'. RWH uses the international date format function from TB.
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/f26ec82001accfd8b102866a5f82fa37bc41828f/chrome/content/core.js#L182

**Comment by BPower0036** [comment]
It is not a big problem, but then I know the international date format function from TB is not the same as Outlook.
