### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by szuksegb** [jeevatkm/ReplyWithHeaderMozilla#139]
Hello!

Could you please translate the addon to Hungarian. I changed the chrome/content/i18n.js in my instance and it looks like a working solution. It would be great if I hadn't patch the addon after every upgrade. Thank you.

```
var i18n = {
"lang": {
"hu": "Magyar", [...]
},
"from": {
"hu": "Feladó:", [...]
},
"to": {
"hu": "Címzett:", [...]
},
"cc": {
"hu": "Másolat:", [...]
},
"subject": {
"hu": "Tárgy:", [...]
},
"date": {
"hu": "Dátum:", [...]
},
"sent": {
"hu": "Dátum:", // actually it means "date", but I prefered this instead of "Küldés dátuma:" which means "sent date" [...]
},
"forwarded_message": {
"hu": "Továbbított levél", [...]
},
"original_message": {
"hu": "Eredeti levél", [...]
},
};
```

**Comment by jeevatkm** [comment]
@szuksegb Thanks for providing details. I will make sure to add it.

I was looking at Google Translate for "Sent" => "Küldött", is it correct?

**Comment by jeevatkm** [comment]
@szuksegb Also, I saw another thing: Can you please validate it?
```
levél => üzenet
```

**Comment by szuksegb** [comment]
> @szuksegb Thanks for providing details. I will make sure to add it.
> 
> I was looking at Google Translate for "Sent" => "Küldött", is it correct?

"Sent" means "Küldött" or "Küldve". If I understood correctly, we use this "Sent" for the date of the original sending. In this case the correct translation is "Küldés dátuma", just I fount it too long. In our cases your extension looks like this:

**Feladó:** Sender Name <sender.name@somewhere.com>
**Dátum:** 2023. október 10., kedd 15:00 CEST
**Címzett:** Recipient Name <recipient.name@somewhere.com>
**Tárgy:** Subject

**Comment by szuksegb** [comment]
> @szuksegb Also, I saw another thing: Can you please validate it?
> 
> ```
> levél => üzenet
> ```

"üzenet" means "message", "levél" means "mail" and we also use it for "e-mail" (officialy "e-mail" is "elekrtonikus levél" but nobody uses it in this way in this country :-) ) I can accept "üzenet" however I prefere "levél" in this context.

**Comment by jeevatkm** [comment]
@szuksegb Understood; I will put the `levél` in the config. Let's see if any users come back and provide input.

**Comment by jeevatkm** [comment]
@szuksegb I have put the `Dátum` for Sent; let's see if any users come back and provide input.

**Comment by jeevatkm** [comment]
@szuksegb created beta version - download link -  https://docs.myjeeva.com/rwh-mozilla/replywithheader-v2.7.0-beta.xpi
