### ISSUE TITLE
"Manage headers" tab looks weird on Windows and Linux

### ISSUE THREAD

**Issue by rostafiychuk** [jeevatkm/ReplyWithHeaderMozilla#14]
![header-win](https://cloud.githubusercontent.com/assets/5871345/12875526/5a29ffae-cdf5-11e5-84e1-b8510a270606.png)

I think it's better to delete this negative margin-top:
```
<hbox align="center" style="margin-top:-15px">
````

Other tabs are fine.

**Comment by jeevatkm** [comment]
It's Done.

**Comment by jeevatkm** [comment]
@rostafiychuk I have addressed other alignment (font size, before separator) issues for Windows. Also introduced 12H or 24H time format and non-english characters handling for header `Cc`.

Can you please try latest v1.4-beta and share your feedback?
http://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v1.4-beta.xpi

**Comment by rostafiychuk** [comment]
Preferences looks fine on Windows and Linux, but there is regression with signature #16
