### ISSUE TITLE
Spellcheck as you type not working

### ISSUE THREAD

**Issue by ahmedhselim** [jeevatkm/ReplyWithHeaderMozilla#142]
Hi,
When I reply or forward, the Spellcheck is not working although it is active. When I remove your add-on, it works fine.

**Comment by IgitBuh** [comment]
I can confirm this. The problem seems to be that an empty line is missing at the beginning. So the written text is being treated as a part of the signature and therefore is not included in the spell checking.

Without this addon, the empty line is present and it works fine.

The same reason also leads to the problem, that if a different signature is selected through the drop-down menu, the email text disappears as part of the replaced signature.

@jeevatkm This is a serious bug, could you please fix this as a priority?

**Comment by IgitBuh** [comment]
v2.7.0-beta solves this problem. Until the fix is officially available, it can be downloaded and installed manually, see #134.

**Comment by willemb2** [comment]
I can confirm that v2.7.0-beta solves the issue of 'spellcheck as you type' not working on reply and forward.

**Comment by jeevatkm** [comment]
@willemb2 @IgitBuh @ahmedhselim Thanks for reaching out. I'm starting to work on the WebExtension version of RWH. I believe this issue will be sorted out with that.

**Comment by jeevatkm** [comment]
@willemb2 @IgitBuh @ahmedhselim I'm working on the WebExtension version of RWH. The branch is [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/tree/WebExtension). 

I require a sample string of the following in multiple languages for a `Plain Text` email.

**Reply**
```
On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
```

**Forward**
```
-------- Forwarded Message --------
Subject: Mozilla Add-on User Rating: ReplyWithHeader
Date: Sun, 28 Apr 2024 00:58:03 -0000
From: Thunderbird Add-ons <nobody@thunderbird.net>
To: jeeva@myjeeva.com
```

**Comment by IgitBuh** [comment]
Would you like a custom translation as close as possible to your sample or do you want us to copy some official translation from somewhere?

Here's a custom translation for German:

```
Antworten

Am 27.04.24 um 17:58 schrieb Thunderbird Add-ons:

Weiterleiten

-------- Weitergeleitete Nachricht --------
Betreff: Mozilla Add-on User Rating: ReplyWithHeader
Datum: Son, 28 Apr 2024 00:58:03 -0000
Von: Thunderbird Add-ons <nobody@thunderbird.net>
An: jeeva@myjeeva.com
```

What languages do you need? I just checked for the output of ChatGPT and it was perfect for German. If it helps, I could provide such a translation for other languages as well, to speed up the process for you.

**Comment by jeevatkm** [comment]
Thanks, @IgitBuh, for your help. In the latest Thunderbird with WebExtension, processing Plain Text emails requires string manipulation and processing. For example, `schrieb` is a keyword used to process the Reply/Reply All. 

I'm looking for a word from the Thunderbird, so google or chatGPT will not help here. I'm currently in the processing of figuring out the way to collect keyword for languages supported by RWH.

**Comment by jeevatkm** [comment]
@ahmedhselim @IgitBuh https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
