### ISSUE TITLE
 New line missing when forwarding message (signature included) #134 

### ISSUE THREAD

**Issue by jpl75** [jeevatkm/ReplyWithHeaderMozilla#143]
For me this is still not working with TB 115.3.3 and ReplyWithHeader 2.6.0.
Unfortunate, as this add-on is extremely useful.

**Comment by jeevatkm** [comment]
@jpl75 I'm starting to work on the WebExtension version of RWH. I will be much better with the latest TB. Thanks for reaching out.

**Comment by jpl75** [comment]
Thanks for the update. Please let me know when you are done. I will happily test. RegardsEnvoyé de mon iPadLe 12 mars 2024 à 19:05, Jeevanandam M. ***@***.***> a écrit :﻿
@jpl75 I'm starting to work on the WebExtension version of RWH. I will be much better with the latest TB. Thanks for reaching out.

**Comment by jeevatkm** [comment]
@jpl75 Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
