### ISSUE TITLE
Sent header crops "Re:" from original subject

### ISSUE THREAD

**Issue by sailor16** [jeevatkm/ReplyWithHeaderMozilla#144]
Hi,
When I reply or forward a mail with "Re:"-subject, the quoted (1st) header subject is cropped by the "Re:" (which is not an exact quote).

PS: I believe that quote-changes are not supposed to happen.
[I am using "Outlook"-Header quoting, but I cannot compare with Outlook on this computer.]

**Comment by jeevatkm** [comment]
@sailor16 do you mind providing a screenshot(s)?

**Comment by ymst396** [comment]
Hi,
I am having the same problem, so I will send you screenshots.
I am using a Japanese OS, so the display is partially in Japanese.

When I reply to an email with the subject "Re: ReplyWithHeader test", it generates a subject "ReplyWithHeader test" with "Re:" removed under "-------- Original Message --------".

I usually set the locale for ReplyWithHeader to Japanese(ja). I changed it to English(en-US) for this report, but this phenomenon occurs regardless of the locale setting.

version:
 Windows 10 Pro 22H2
 Thunderbird 115.9.0
 ReplyWithHeader 2.6.0
![TB-RWH-option-1](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/165245236/d19ce309-4d38-4e03-8cea-f530913693c9)
![TB-RWH-option-2](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/165245236/23ea46da-ea56-4e60-b38d-f3f876ae943f)
![TB-RWH-reply](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/165245236/7d59c3b0-6408-40c0-853e-80d4ee431729)

**Comment by jeevatkm** [comment]
Thanks, @ymst396, for the inputs.

@sailor16, @ymst396  I'm working on the WebExtension version of RWH. The branch is [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/tree/WebExtension). 

I require a sample string of the following in multiple languages for a `Plain Text` email.

**Reply**
```
On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
```

**Forward**
```
-------- Forwarded Message --------
Subject: Mozilla Add-on User Rating: ReplyWithHeader
Date: Sun, 28 Apr 2024 00:58:03 -0000
From: Thunderbird Add-ons <nobody@thunderbird.net>
To: jeeva@myjeeva.com
```

**Comment by jeevatkm** [comment]
@sailor16 https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
