### ISSUE TITLE
Replace div with span

### ISSUE THREAD

**Issue by rocky7x** [jeevatkm/ReplyWithHeaderMozilla#145]
Hi,

Just a quick suggestion: could you please replace the HTML prefix and suffix div with span, since when sending the mail to Outlook, it puts space between the lines, so they look as separate paragraphs?

Thank you very much.
Cheers

**Comment by rocky7x** [comment]
I did some corrections to the core.js file myself and got a bit better formatting of the header, which mimics the original Outlook header much better. I attach the complete XPI file here (as ZIP, just rename it to XPI), it has add-on version 2.6.3. You can compare my file with yours and if you like it, you can adopt the changes. What I did:

1. replace hr horizontal line tag with div with border-top (this is the way Outlook does it)
2. replace all other divs with spans, in order to avoid Outlook putting white space between lines
3. corrected the margin in the div at the top, using padding instead of margin (this is the way Outlook does it)
4. explicitly added 0 margin into the htmlTagPrefix variable to prevent the white-spacing done by Outlook parsing

Cheers..
[replywithheader-2.6.3-tb.zip](https://github.com/jeevatkm/ReplyWithHeaderMozilla/files/13439618/replywithheader-2.6.3-tb.zip)

**Comment by jeevatkm** [comment]
@rocky7x Thanks for your contribution. I'm sorry for the delayed response. I'm starting to work on webextension of the Add-on, I will incorporate your inputs. Thanks.

**Comment by jeevatkm** [comment]
Hello @rocky7x - 

I have created an RWH {Web|Mail}Extension version of the add-on. The v3 version is a complete rewrite from the ground up. Please try it and share feedback on this thread https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103.
I have developed a significantly improved and capable RWH in v3. You will find it to be a significant enhancement to your workflow.

Download Link: https://docs.myjeeva.com/rwh-mozilla/replywithheader-v3.0.0.beta1.xpi

It requires minimum TB v125 - https://ftp.mozilla.org/pub/thunderbird/releases/125.0/

Cheers, Jeeva
