### ISSUE TITLE
Thunderbird 125 disable this extension

### ISSUE THREAD

**Issue by gabri25ele** [jeevatkm/ReplyWithHeaderMozilla#146]
https://ftp.mozilla.org/pub/thunderbird/releases/125.0/

an update will be necessary 😘

**Comment by jeevatkm** [comment]
@gabri25ele Thanks for reporting it. I'm working on a WebExtension add-on for the upcoming July TB ESR release.

**Comment by jeevatkm** [comment]
@gabri25ele I'm working on the WebExtension version of RWH. The branch is [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/tree/WebExtension). 

I require a sample string of the following in multiple languages for a `Plain Text` email.
```
On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
```

**Comment by gabri25ele** [comment]
> @gabri25ele I'm working on the WebExtension version of RWH. The branch is [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/tree/WebExtension).
> 
> I require a sample string of the following in multiple languages for a `Plain Text` email.
> 
> **Reply**
> 
> ```
> On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
> ```
> 
> **Forward**
> 
> ```
> -------- Forwarded Message --------
> Subject: Mozilla Add-on User Rating: ReplyWithHeader
> Date: Sun, 28 Apr 2024 00:58:03 -0000
> From: Thunderbird Add-ons <nobody@thunderbird.net>
> To: jeeva@myjeeva.com
> ```

mine (in italian)

Il 27/04/2024 alle 17:58, Thunderbird ha scritto:

-------- messaggio originale --------
Da: Kissashop [mailto:info@kissashop.it]
Inviata: mercoledì 24 aprile 2024 alle ore 12:32
A: myemail@gmail.com
Oggetto: TERRY DOSON PRESENTA

**Comment by jeevatkm** [comment]
Thanks, @gabri25ele, for your help.

**Comment by jeevatkm** [comment]
Hello @gabri25ele - 

I have created an RWH {Web|Mail}Extension version of the add-on. The v3 version is a complete rewrite from the ground up. Please try it and share feedback on this thread https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103.
I have developed a significantly improved and capable RWH in v3. You will find it to be a significant enhancement to your workflow.

Download Link: https://docs.myjeeva.com/rwh-mozilla/replywithheader-v3.0.0.beta1.xpi

It requires minimum, TB v125 - https://ftp.mozilla.org/pub/thunderbird/releases/125.0/

Cheers, Jeeva

**Comment by gabri25ele** [comment]
problem in "object"

old version
![old](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/33927879/f6db9f4a-2624-4c87-86e0-14665d7f9cd5)

more correct 
the "RE" is removed

new version
![new](https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/33927879/ba14d485-76e2-45bd-b93c-4da81fa146e0)
the "RE" is present

;)

then I found that it's not good for **newsserver accounts**, ok they should be disabled. 
But could they have already been disabled at the start? 
Or is it even better to have an answer made specifically for this type of account?
