### ISSUE TITLE
Does not work work Owl addon, both OWA and EWS accounts

### ISSUE THREAD

**Issue by bleez99** [jeevatkm/ReplyWithHeaderMozilla#153]
I had mentioned that nothing apparently happens when replying to a message on the addons site.  
Further troubleshooting shows that this addon currently works only with IMAP accounts.  This combo of Owl and Reply With Header worked fine on TB 115.

**Comment by jeevatkm** [comment]
@bleez99 FYI, RWH v3 is rewritten completly from the ground up. I'm wondering whether this could be causing an issue for you!
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/477ea5203e87529003957031daf188160129b52e/background.js#L28

Do you know the value of the account type by any chance? so that we can add it.

**Comment by bleez99** [comment]
Hi. When I have a chance I'll run through the debugger. Not sure if Owl would pass anything but an educated guess would be ews or owa. There's a third for Active Sync too. I haven't tried that. 

Question, why would you want to check the account type? Shouldn't just let it work for whatever account you choose? 

Just a thought. 

I'll test by removing that condition and see if the reply headers start to work and go from there. 

--
Bryan

On July 20, 2024 12:55:00 PM "Jeevanandam M." ***@***.***> wrote:


@bleez99 FYI, RWH v3 is rewritten completly from the ground up. I'm wondering whether this could be causing an issue for you!
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/477ea5203e87529003957031daf188160129b52e/background.js#L28 <https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/477ea5203e87529003957031daf188160129b52e/background.js#L28> 

Do you know the value of the account type by any chance? so that we can add it.

**Comment by jeevatkm** [comment]
I was facing some issue when developing for new Thunderbird version.  I have commented out the condition and enabled the  debug logger. Can you try this version and share your feedback?
[replywithheader-v3.0.1-debug.xpi.zip](https://github.com/user-attachments/files/16323281/replywithheader-v3.0.1-debug.xpi.zip)

**Comment by bleez99** [comment]
Still not working. I tried, but cannot find the account in the configuration drop-down. 

The imap version of the account is fine. 

--
Bryan

On July 21, 2024 2:21:57 AM "Jeevanandam M." ***@***.***> wrote:


I was facing some issue when developing for new Thunderbird version. I have commented out the condition and enabled the debug logger. Can you try this version and share your feedback?
replywithheader-v3.0.1-debug.xpi.zip <https://github.com/user-attachments/files/16323281/replywithheader-v3.0.1-debug.xpi.zip>

**Comment by jeevatkm** [comment]
@bleez99 Thanks for trying. I have prepared debug2 version and also commented out code flow and added debug log line.
Can you install this debug2 version and share the debug console log details?

Steps to reach the debug console log:

- Go to Add-ons Manager 
- click Settings wheel icon 
- click Debug Add-ons 
- find the ReplyWithHeader add-on 
- click Inspect button
- now debug console window appears

[replywithheader-v3.0.1-debug2.xpi.zip](https://github.com/user-attachments/files/16330336/replywithheader-v3.0.1-debug2.xpi.zip)

**Comment by jeevatkm** [comment]
@bleez99 Did you get a chance to try it out?

**Comment by bleez99** [comment]
I'm convinced it's Owl. 
I sent a support ticket and nothing. 

And that's a paid addon too. 
Can you install Owl and try an outlook account?

It's free for one month. 




--
Bryan

On July 23, 2024 4:58:23 PM "Jeevanandam M." ***@***.***> wrote:


@bleez99 Did you get a chance to try it out?

**Comment by bleez99** [comment]
I received a reply finally from the Owl people. 
Your addon is fine. 
It's their problem. 
They even had to submit a PR to Mozilla for it. 

Thanks for your attention and willingness to help. 
Looks like I just have to wait for the other issues to get straightened out. 

Thanks again,
--
Bryan

On July 23, 2024 4:58:23 PM "Jeevanandam M." ***@***.***> wrote:


@bleez99 Did you get a chance to try it out?

**Comment by jeevatkm** [comment]
@bleez99 Good, finally we got a lead on the issue.  

Is it possible to get `account.type` info from the Owl addon team? so that I could incorporate that into RWH.

----

Whenever, you get the resolution; could you update the review and stars on [TB add-on portal](https://addons.thunderbird.net/en-US/thunderbird/addon/replywithheader/) and close this issue.

**Comment by bleez99** [comment]
They are real jerks. 

When I ran your addon in debugging mode, nothing was found. 

They claim it's Thunderbird, and they have a PR pending for this. 

I guess we'll just have to wait. Once the PR is made public perhaps I can help. 

They aren't very cooperative AND it's a paid addon. 

--
Bryan

On July 25, 2024 11:45:22 AM "Jeevanandam M." ***@***.***> wrote:


@bleez99 Good, finally we got a lead on the issue.

Is it possible to get account.type info from the Owl addon team? so that I could incorporate that into RWH.

--------------------------------
Whenever, you get the resolution; could you update the review and stars on TB add-on portal <https://addons.thunderbird.net/en-US/thunderbird/addon/replywithheader/> and close this issue.

**Comment by jeevatkm** [comment]
I see, Thanks. Let me see know what I can find.

**Comment by jeevatkm** [comment]
@bleez99 Did you get a issue resolved from Owl add-on? Do you mind updating your review and stars for RWH add-on?

**Comment by Lalilalulalam** [comment]
I'm experiencing same behavior. Is there anything I can do to have sort this one out?

**Comment by bleez99** [comment]
Me, no. I work as a full time developer and really want to walk away from code after eight hours. 

The nasty Owl developers claim to have a PR for this issue but it hasn't been merged and I even checked the nightly builds to see if it was corrected. They actually remove negative reviews from their addon page. 

The current code base only recognizes IMAP and POP3. Not sure if Local accounts are even identified as such. So, your add on should work, in theory, with local accounts too.  

A lot of people, including me, use Local for archives and there might be the possibility of replying to an old archived message. Unlikely, but completely possible. 

--
Bryan

On August 8, 2024 9:10:24 AM Lalilalulalam ***@***.***> wrote:


I'm experiencing same behavior. Is there anything I can do to sort this one out?

**Comment by jeevatkm** [comment]
@Lalilalulalam @bleez99 The imap and pop3 condition has been removed, I will be released in the upcoming v3.1.0  So RWH will work across emails unless someother add-on break it; recently @bleez99 found Owl add-on was causing an issue.

**Comment by jeevatkm** [comment]
@bleez99 @Lalilalulalam RWH v3.1.0 release submitted to ATN review. This version has imap and pop3 condition removed.
