### ISSUE TITLE
Remove All Quote Indentation

### ISSUE THREAD

**Issue by andymaxo** [jeevatkm/ReplyWithHeaderMozilla#154]
As you know, Quote indentation causes the email messages layout untidy on thunderbird. I think all quotes should align left, like outlook. so I hope ReplyWithHeader3.0 can add a feature, that is: remove quote indentation. I found Apple mail. it make quote indentation a option. you can enable quote indentation, or disable quote indentation.

![2024-07-18_165904](https://github.com/user-attachments/assets/4765f92e-2da1-488d-89b0-7f4383c55afa)

**Comment by andymaxo** [comment]
Dear Jeeva! When will ReplyWithHeaderMozilla 3.1.0 release?

**Comment by jeevatkm** [comment]
@andymaxo I will have to allocate time to analyze and develop the solution. I'm sorry, I'm unable to provide a timeline commitment for this new enhancement, but I will aim for it. Thanks.

**Comment by jeevatkm** [comment]
@andymaxo I created this development version. You could do this test and share feedback about quote indentation.
Extract the zip and install it.
[replywithheader-v3.1.0-dev.xpi.zip](https://github.com/user-attachments/files/16435821/replywithheader-v3.1.0-dev.xpi.zip)

**Comment by jeevatkm** [comment]
@andymaxo I have created the next version of the dev. This addresses the quote issue. 

There is no need for screenshots; reply here with your feedback.
[replywithheader-v3.1.0-dev.xpi.zip](https://github.com/user-attachments/files/16449865/replywithheader-v3.1.0-dev.xpi.zip)

**Comment by andymaxo** [comment]
Dear Jeeva,

I tested this new version, the quote issue already sovled. it can work.
but another issue: when Reply/Reply All, it display a icon, this issue still exists.



If you have any questions, please do not hesitate to contact us,

and we will be more than happy to assist you.

--
Best regards,
Andy Ma
--------------
Email: ***@***.***

________________________________

**Comment by jeevatkm** [comment]
@andymaxo Thanks for testing the quote issue and for the feedback. Let me see what I can do for the border color on Apple Mail.

Regarding the icon on the compose window, I do not know how to solve it - I have reached out to the TB forum, no luck - Please read https://thunderbird.topicbox.com/groups/addons/T934e43df391a863c/need-help-to-identify-an-issue-on-compose-window
