### ISSUE TITLE
Preserve the user selected locale value from the Options UI

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeaderMozilla#155]
Text taken from this thread - https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/108#issuecomment-2259772111

I finally managed to install fresh TB 128.0.1 with RWH 3.0.0 (release version), and have used that now for couple of days. In general looks good but there is also one bug. I also have some comments/suggestions:

RWH locale resets to TB user interface locale at every TB start

In my case I like to keep TB user interface set to my local language (Finnish in my case), but set RWH to en-US to get "standard" written headers into email replies or forwards. I can set RWH locale in its settings, but it resets to TB user interface language at every TB start, which is a bug to my mind.

**Comment by jeevatkm** [comment]
@anttiisoaho If you want, try this dev version until the release.

[replywithheader-v3.1.0-dev.xpi.zip](https://github.com/user-attachments/files/16483132/replywithheader-v3.1.0-dev.xpi.zip)

**Comment by anttiisoaho** [comment]
> @anttiisoaho If you want, try this dev version until the release.
> 
> [replywithheader-v3.1.0-dev.xpi.zip](https://github.com/user-attachments/files/16483132/replywithheader-v3.1.0-dev.xpi.zip)

Locale setting is preserved with this one - thank you

**Comment by jeevatkm** [comment]
@anttiisoaho Thanks for the feedback!

**Comment by bich30** [comment]
Thank you very much for the new version.

I also have the same problem and when installing the new version it gives an error, indicating that the file may be damaged.

Any advice/help to install it?

Thanks!!!

**Comment by bich30** [comment]
Ok!!

Thanks!!
