### ISSUE TITLE
Language settings question 

### ISSUE THREAD

**Issue by Hanna-Chang** [jeevatkm/ReplyWithHeaderMozilla#159]
Hi,

I want to know why every time I open Thunderbird, I need to set up the ReplyWithHeader’s language again. Can I lock the language in English permanently?

*My computer is running a Chinese version of Windows, and every time I open Thunderbird, the ReplyWithHeader’s language column goes back to Chinese.

Thank you for the help. 
![IMG_9163](https://github.com/user-attachments/assets/a68fd201-55d5-41c2-9103-169d5d44df9d)

**Comment by jeevatkm** [comment]
@Hanna-Chang It is a bug. Yesterday, I have fixed it. Here is the info #155. There is a dev build version here: https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/155#issuecomment-2267183578
