### ISSUE TITLE
Regression with signature in 1.4-beta

### ISSUE THREAD

**Issue by rostafiychuk** [jeevatkm/ReplyWithHeaderMozilla#16]
with 1.3:
![screenshot from 2016-02-12 11 21 55](https://cloud.githubusercontent.com/assets/5871345/13002969/49342e7a-d17b-11e5-8ca0-c7b60a2393ec.png)

with 1.4-beta:
![screenshot from 2016-02-12 11 23 02](https://cloud.githubusercontent.com/assets/5871345/13002971/51825980-d17b-11e5-88ca-2146c6d23c0a.png)

I have to delete this gap every time.

**Comment by jeevatkm** [comment]
Just wanna to check with you. Do you have any value assigned here (this is default values)?

<img width="407" alt="header-line-space" src="https://cloud.githubusercontent.com/assets/1175977/13380441/50ed584c-ddf8-11e5-9be9-8c1b49708d59.png">

**Comment by rostafiychuk** [comment]
I have these default values. I tried to change "Before separator" to any number and always get one extra. Now I checked it on Windows and behavior is the same.

**Comment by rostafiychuk** [comment]
I have one older beta 1.4 from http://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v1.4-beta.xpi downloaded on Feb 7 and it works fine with older one.

**Comment by jeevatkm** [comment]
Thanks for the inputs. I'm currently working on it.

**Comment by jeevatkm** [comment]
It's done!

**Comment by rostafiychuk** [comment]
Thanks! Latest beta works fine.
@jeevatkm are you going to publish new release soon?

**Comment by jeevatkm** [comment]
Thanks @rostafiychuk. It might go to next week, since I'm awaiting feedback from couple of users.

**Comment by rostafiychuk** [comment]
Do somebody find any new problem in 1.4 beta?

**Comment by jeevatkm** [comment]
Yes, user reported an issue for Postbox client.

**Comment by rostafiychuk** [comment]
I there any progress on it? I didn't find any new open issue there.

**Comment by jeevatkm** [comment]
Yes, no open issue :) Currently I'm working on AMO review comments.

**Comment by jeevatkm** [comment]
@rostafiychuk I have finally submitted `v1.4` addon to AMO, its pending for review. Sorry for delay.
