### ISSUE TITLE
RWH cancels "automatically quote original message when replying"

### ISSUE THREAD

**Issue by O-Gopal** [jeevatkm/ReplyWithHeaderMozilla#161]
Thank you for the excellent extension, which I've been using for some time now. 

On a fresh install. . . 

RWH 2.6.0 with TB 115.13.0 on Fedora Linux 40:

Enabling RWH blocks the setting "automatically quote original message when replying" (under Account Settings--> Composition & Addressing --> Composition"). The TB setting can be chosen, and the original message appears in the reply--but not set off as quoted.

Disabling RWH restores the original TB functionality.

**Comment by jeevatkm** [comment]
@O-Gopal, you could uncheck this setting in the option UI.
* Cleanup first level blockquote color

PS: In the upcoming version 3.1.0, please uncheck the following.
* Cleanup first level blockquote alignment and color
* Cleanup all level blockquote alignment and color

**Comment by O-Gopal** [comment]
Thank you, @jeevatkm. 

Yes, unticking "Cleanup the blockquote colors" solved the issue for me.

Thank you again.
