### ISSUE TITLE
Setting "trans.subject.prefix" cannot be disabled

### ISSUE THREAD

**Issue by ygoe** [jeevatkm/ReplyWithHeaderMozilla#165]
Whatever I choose in the add-on's options as "Transform subject prefix", it's always transformed. I have already added additional checks in two more places, but that setting is really true in the code, no matter what I select. Somehow the settings don't seem work here. Investigating further...

**Comment by ygoe** [comment]
I found and fixed it. Can create a PR once my other PR has been merged. I trimmed some whitespace in a conflicting line... So I don't want to waste time with handling format issues...

**Comment by jeevatkm** [comment]
@ygoe Did you mean this condition has an issue?
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/1a48d04c4c57328ba601b3142a97bdad294939a6/modules/compose.mjs#L123
