### ISSUE TITLE
3.1.0 Still doesn't find Owl based accounts

### ISSUE THREAD

**Issue by bleez99** [jeevatkm/ReplyWithHeaderMozilla#167]
Still working fine with IMAP, but in the settings dropdown for the addon, the Owl account still doesn't appear as a choice.
Replying to an Owl message defaults to TB's default quoting style.

TB 128.1 130+

**Comment by jeevatkm** [comment]
@bleez99 I see, could you share steps to replicate at my end? it will be much easier to figure out the issue.

**Comment by bleez99** [comment]
Just set up a regular IMAP account, and an Owl account. 

Install the addon. 
In the addon settings, you will only see the IMAP account. The Owl account is missing from the drop down. 

Reply to any message from the Owl account. 
Just the default Thunderbird quote. 

Reply to any IMAP account message, perfect looking Outlook style quotes. 

Apparently the addon cannot "see" the Owl based account. 

I tried this on a nightly build. (I force install by modifying the manifest). I could see my Owl account in the drop-down!

Unfortunately, Owl messages are blank on the nightly, and I can't test from there. 

--
Bryan

On August 10, 2024 2:24:16 PM "Jeevanandam M." ***@***.***> wrote:


@bleez99 I see, could you share steps to replicate at my end? it will be much easier to figure out the issue.

**Comment by jeevatkm** [comment]
@bleez99 I have installed Owl add-on, its asking for office365 or exchange account, I do not have one. 
I tried to configure my outlook.live.com account, its not working.

[replywithheader-v3.1.1-debug.xpi.zip](https://github.com/user-attachments/files/16571653/replywithheader-v3.1.1-debug.xpi.zip)

Install this debug version. I have added this line `console.log(account);` in it.

Go to Add-ons Manager -> click on settings icon -> click Debug Add-ons -> look for RWH extension -> click inspect button -> you will get console window -> copy the all log lines and email to me

**Comment by jeevatkm** [comment]
@bleez99 Did you get a chance to get me logs?

**Comment by bleez99** [comment]
Check your mail I sent them yesterday. 

Thanks,
--
Bryan

On August 12, 2024 3:55:36 PM "Jeevanandam M." ***@***.***> wrote:


@bleez99 Did you get a chance to get me logs?

**Comment by jeevatkm** [comment]
@bleez99 I just checked my emails once again, I didn't see any email regarding logs. Can you check the my email address `jeeva@myjeeva.com`?

**Comment by bleez99** [comment]
I replied directly to your email. 
I'll try again tomorrow if I have time. 

--
Bryan

On August 12, 2024 8:24:08 PM "Jeevanandam M." ***@***.***> wrote:


@bleez99 I just checked my emails once again, I didn't see any email regarding logs. Can you check the my email address ***@***.***?

**Comment by bleez99** [comment]
Regardless, the debugging lines only revealed the IMAP and Local accounts. 

--
Bryan

On August 12, 2024 8:24:08 PM "Jeevanandam M." ***@***.***> wrote:


@bleez99 I just checked my emails once again, I didn't see any email regarding logs. Can you check the my email address ***@***.***?

**Comment by jeevatkm** [comment]
> I replied directly to your email.  I'll try again tomorrow if I have time. 

I'm sorry, I do not have your direct email address. Also I do not recall sending any email directly to you.

**Comment by jeevatkm** [comment]
> Regardless, the debugging lines only revealed the IMAP and Local accounts. 

In TB 128 and above, this line of code should return all mail accounts regardless of the type -
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/3023cbb22437383ade1362d2201d9f2445069b8b/modules/accounts.mjs#L25

Then, RWH uses the list to configure it. I have added the debug line after line 27 to log accounts individually.

**Comment by bleez99** [comment]
I replied to the GitHub generated email from the issue I posted. 

--
Bryan

On August 12, 2024 8:42:57 PM "Jeevanandam M." ***@***.***> wrote:


I replied directly to your email.  I'll try again tomorrow if I have time. 

I'm sorry, I do not have your direct email address. Also I do not recall sending any email directly to you.

**Comment by bleez99** [comment]
Please resend the link to your latest debug version. 

--
Bryan

On August 12, 2024 8:47:00 PM "Jeevanandam M." ***@***.***> wrote:


Regardless, the debugging lines only revealed the IMAP and Local accounts. 

In TB 128 and above, this line of code should return all mail accounts regardless of the type -
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/3023cbb22437383ade1362d2201d9f2445069b8b/modules/accounts.mjs#L25 <https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/3023cbb22437383ade1362d2201d9f2445069b8b/modules/accounts.mjs#L25> 

Then, RWH uses the list to configure it. I have added the debug line after line 27 to log accounts individually.

**Comment by jeevatkm** [comment]
> I replied to the GitHub generated email from the issue I posted. 

Typically, for this action, all the responses should be present in the issue—https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/167; however, I do not see them on the GitHub issue. You can validate it, too.

> Please resend the link to your latest debug version. 

Here you go - [replywithheader-v3.1.1-debug.xpi.zip](https://github.com/user-attachments/files/16571653/replywithheader-v3.1.1-debug.xpi.zip)

**Comment by jeevatkm** [comment]
@bleez99 Can you share debug log info?

**Comment by jeevatkm** [comment]
@bleez99 Can you help with debug log? 
As mentioned before, I do not have exchange or office 365 mail accounts, so I won't be able to test it at my end.

**Comment by TGRHavoc** [comment]
> @bleez99 Can you help with debug log? As mentioned before, I do not have exchange or office 365 mail accounts, so I won't be able to test it at my end.

It looks like the function call doesn't return OWL accounts at all:
```
export async function all() {
    let accounts = await messenger.accounts.list();
    console.log("All accounts: ", accounts);
    let res = [];
    for (let account of accounts) {
        if (account.type === 'none') { continue };
        res.push({
            'id': account.id,
            'name': account.name,
            'type': account.type
        });
    }
    return res;
}
```
![image](https://github.com/user-attachments/assets/1ed298b5-5308-46a3-b0b9-87f924779237)

**Comment by TGRHavoc** [comment]
> > @bleez99 Can you help with debug log? As mentioned before, I do not have exchange or office 365 mail accounts, so I won't be able to test it at my end.
> 
> It looks like the function call doesn't return OWL accounts at all:
> 
> ```
> export async function all() {
>     let accounts = await messenger.accounts.list();
>     console.log("All accounts: ", accounts);
>     let res = [];
>     for (let account of accounts) {
>         if (account.type === 'none') { continue };
>         res.push({
>             'id': account.id,
>             'name': account.name,
>             'type': account.type
>         });
>     }
>     return res;
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1770893/359221887-1ed298b5-5308-46a3-b0b9-87f924779237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTYyMTEsIm5iZiI6MTcyNDA5NTkxMSwicGF0aCI6Ii8xNzcwODkzLzM1OTIyMTg4Ny0xZWQyOThiNS01MzA4LTQ2YTMtYjBiOS04N2Y5MjQ3NzkyMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTkzMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTAyY2FjMGNiZDIwMGY3YWMyNzcwYTVkYmFhMTFmYTBkODNjYjNmMmUzNWRmMjBlNDk4OWYwODRlNjE1ODI0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VN_wLmUApw54z-apsl_agelov93pu_QKa7kiki0Zi-Q)

Some further investigation (not sure if this actually helps) but, OWL accounts show up when using the [identities api](https://webextension-api.thunderbird.net/en/stable/identities.html):
```
    let identities = await messenger.identities.list();
    console.log("All identities: ", identities);
    let accountFromIdentity = await messenger.accounts.get(identities[0].accountId);
    console.log("Account from identity: ", accountFromIdentity);
```
However, it doesn't appear when you "get" the account...

I am completely new to thunderbird extension development so, I may be missing something... I would love to contribute if I was pushed in the right direction :)
![image](https://github.com/user-attachments/assets/fd26b710-be08-4d45-b388-499b7c1a8723)

**Comment by jeevatkm** [comment]
@TGRHavoc Wow, thanks for your help. 

Currently, RWH expects this line `let accounts = await messenger.accounts.list();` to return all mail accounts. 

If we get all accounts (including OWL) values mapped from identities API in the above function on your comment, we can make it work for all.

Would you like to attempt it? OR, if you can copy the complete console log lines as a string and give it to me, I will update the code flow, and you could help me test it. Let me know.

**Comment by bleez99** [comment]
I will try, I've been kind of busy with work and the last thing I want to do is debug more code. 

I've seen that line of code, and in the console we're only returning IMAP and I think local. Owl is definitely not there. 

If you remember, I told you the extra friendly Owl people told me it's a Thunderbird bug along with a PR they claim to have submitted. 

I'm kind of sceptical about that as I don't see it in beta or in nightly builds. We might be stuck with a Thunderbird bug. 

I forced your plug-in to load by modifying the manifest in beta and the nightly builds. 

--
Bryan

On August 19, 2024 4:15:22 PM "Jeevanandam M." ***@***.***> wrote:


@TGRHavoc Wow, thanks for your help.

Currently, RWH expects this line let accounts = await messenger.accounts.list(); to return all mail accounts.

If we get all accounts (including OWL) values mapped from identities API in the above function on your comment, we can make it work for all.

Would you like to attempt it? OR, if you can copy the complete console log lines as a string and give it to me, I will update the code flow, and you could help me test it. Let me know.

**Comment by bleez99** [comment]
It doesn't return anything but IMAP and if I recall correctly, local. Owl, no. 

The Owl people are blaming Thunderbird. They claim to have submitted a PR. 

Very sceptical about that PR. 

--
Bryan

On August 19, 2024 4:05:38 PM Jordan Dalton ***@***.***> wrote:


@bleez99 Can you help with debug log? As mentioned before, I do not have exchange or office 365 mail accounts, so I won't be able to test it at my end.

It looks like the function call doesn't return OWL accounts at all:


export async function all() {
    let accounts = await messenger.accounts.list();
    console.log("All accounts: ", accounts);
    let res = [];
    for (let account of accounts) {
        if (account.type === 'none') { continue };
        res.push({
            'id': account.id,
            'name': account.name,
            'type': account.type
        });
    }
    return res;
}


 <https://private-user-images.githubusercontent.com/1770893/359221887-1ed298b5-5308-46a3-b0b9-87f924779237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTYyMTEsIm5iZiI6MTcyNDA5NTkxMSwicGF0aCI6Ii8xNzcwODkzLzM1OTIyMTg4Ny0xZWQyOThiNS01MzA4LTQ2YTMtYjBiOS04N2Y5MjQ3NzkyMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTkzMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTAyY2FjMGNiZDIwMGY3YWMyNzcwYTVkYmFhMTFmYTBkODNjYjNmMmUzNWRmMjBlNDk4OWYwODRlNjE1ODI0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VN_wLmUApw54z-apsl_agelov93pu_QKa7kiki0Zi-Q> 

Some further investigation (not sure if this actually helps) but, OWL accounts show up when using the identities api <https://webextension-api.thunderbird.net/en/stable/identities.html> :


    let identities = await messenger.identities.list();
    console.log("All identities: ", identities);
    let accountFromIdentity = await messenger.accounts.get(identities[0].accountId);
    console.log("Account from identity: ", accountFromIdentity);


However, it doesn't appear when you "get" the account...

I am completely new to thunderbird extension development so, I may be missing something... I would love to contribute if I was pushed in the right direction :)
image.png (view on web) <https://github.com/user-attachments/assets/fd26b710-be08-4d45-b388-499b7c1a8723>

**Comment by jeevatkm** [comment]
@TGRHavoc I'm sorry, I kind of jumped the gun with the implementation using your lead.

@TGRHavoc @bleez99 can you try this v3.2.0-dev version? I have changed the concept from account to identities across the RWH.

[replywithheader-v3.2.0-dev.xpi.zip](https://github.com/user-attachments/files/16668379/replywithheader-v3.2.0-dev.xpi.zip)

**Comment by bleez99** [comment]
It's working!
 I have an IMAP and Owl account set up - Currently using Owl for the calendar and contacts.
 
 Both show up in the settings and it's looking good!
 
 
 
 
On 8/19/2024 11:11 PM, Jeevanandam M. wrote:
 
 

@TGRHavoc I'm sorry, I kind of jumped the gun with the implementation using your lead.

 

@TGRHavoc @bleez99 can you try this v3.2.0-dev version? I have changed the concept from account to identities across the RWH.

 

replywithheader-v3.2.0-dev.xpi.zip

 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you were mentioned.Message ID: ***@***.***>

 
 
-- 
 Bryan

**Comment by bleez99** [comment]
Replying again.
 I am now able to delete the IMAP account, which for some strange reason Exchange admins hate.
 They claim it's "insecure" when both methods use OAuth tokens for authentication.
 The truth is, Microsoft just hates its users, loves to take internet standards, dismiss them, and make incompatible internal email formats.
 Do you know the history about why they call it Exchange?
 
 Regards,
 
 
 
On 8/19/2024 11:11 PM, Jeevanandam M. wrote:
 
 

@TGRHavoc I'm sorry, I kind of jumped the gun with the implementation using your lead.

 

@TGRHavoc @bleez99 can you try this v3.2.0-dev version? I have changed the concept from account to identities across the RWH.

 

replywithheader-v3.2.0-dev.xpi.zip

 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you were mentioned.Message ID: ***@***.***>

 
 
-- 
 Bryan

**Comment by jeevatkm** [comment]
@bleez99 Thanks for confirming, latest identity based implementation is working. Kindly update TB add-on review. 
I do not know the history, I will look it up.

Thanks again @TGRHavoc for your analysis and input, which helped to resolve the unexpected behaviour of OWL accounts.

**Comment by bleez99** [comment]
I updated my reviews.
 Thanks for working on this!
 I wish every dev cared as much as you do.
 
 
 
On 8/20/2024 12:00 PM, Jeevanandam M. wrote:
 
 

@bleez99 Thanks for confirming, latest identity based implementation is working. Kindly update TB add-on review.
 I do not know the history, I will look it up.

 

Thanks again @TGRHavoc for your analysis and input, which helped to resolve the unexpected behaviour of OWL accounts.

 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you were mentioned.Message ID: ***@***.***>

 
 
-- 
 Bryan

**Comment by jeevatkm** [comment]
Thank you @bleez99
