### ISSUE TITLE
Titles appear as "undefined"

### ISSUE THREAD

**Issue by fsbp70** [jeevatkm/ReplyWithHeaderMozilla#168]
Titles for From,Sent, To, SUbject appear as undefined
![Captura de pantalla 2024-08-17 064214](https://github.com/user-attachments/assets/71833370-09e4-41ef-a20a-b111ac52de2a)

**Comment by fsbp70** [comment]
Using Thunderbird 128.0.1 (64 bit)

**Comment by jeevatkm** [comment]
@fsbp70 It seems some unhandled for locale value. Can you share your locale info?
Also, can you go to add-on options to select a locale explicitly from the drop down and try it?

**Comment by jeevatkm** [comment]
@fsbp70 Any update?
