### ISSUE TITLE
proposed enhancement for RWH in thunderbird

### ISSUE THREAD

**Issue by ndanieley** [jeevatkm/ReplyWithHeaderMozilla#17]
it would be very nice to have the ability to change the color and density of the 'thin blue separator' line.

**Comment by jeevatkm** [comment]
Thanks, you can expect in v1.4 release.

**Comment by jeevatkm** [comment]
I have implemented this functionality.  Can you please try this v1.4-beta and share your feedback?

http://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v1.4-beta.xpi

**Comment by ndanieley** [comment]
that's just what we wanted! my user is very happy. of course, your prompt and very helpful response leads us to another request: could we have an option to include space below the separator!

**Comment by jeevatkm** [comment]
I'm glad you like it.  "could we have an option to include space below the separator!"

It is already present, please use it. 
<img width="402" alt="header-line-spaces" src="https://cloud.githubusercontent.com/assets/1175977/13362235/ead3304e-dc77-11e5-8922-498fa184229a.png">

*If you get a chance, please add your review comment for this feature :)*

**Comment by ndanieley** [comment]
oh, sorry, I was looking for 'after separator'. 'before header' works just fine! thanks so much!

**Comment by jeevatkm** [comment]
It's done :)
