### ISSUE TITLE
cover cases when 'wrote:' keyword not found in plain text reply mode

### ISSUE THREAD

**Issue by masked-shizuma** [jeevatkm/ReplyWithHeaderMozilla#173]
Hello,

I am using ReplyWithHeader version 3.1.0 in the following environment:
Windows 10 Pro 64bit 22H2
Thunderbird 128.1.1esr (64bit)

When I use 'Reply' to respond to an email, only '-------- Original Message --------' is displayed, and the From, Sent, To, and Subject fields are not shown. However, when I use 'Forward,' the From, Sent, To, and Subject fields are displayed below '-------- Forwarded Message --------.' 
I would like the From, Sent, To, and Subject fields to be displayed when I use 'Reply' as well. Could you please give me some advice?
I apologize for my lack of proficiency in English.
Thank you.

**Comment by jeevatkm** [comment]
@masked-shizuma, maybe some errors are happening in your TB while replying. Can you get me the error log for investigation?

Steps to reach the debug console log:

- Go to Add-ons Manager 
- click the Settings wheel icon 
- click Debug Add-ons 
- find the ReplyWithHeader add-on 
- click Inspect button
- now, the debug console window appears

Once the console window is opened, perform a reply operation and see what errors appear in the console log. Share those with me.

**Comment by masked-shizuma** [comment]
Thank you for your reply.

Since this is my first time using the debug console window, I'm not sure where to look. The content of the 'Inspector' tab on the left shows:

```html
<!DOCTYPE html>
<html lang="en"> event
 <head>...</head>
 <body>
 </body>
<html>
```

The content of the 'Console' tab shows:

```plaintext
RWH:INFO:: Addon loaded successfully
```

The content of the 'Debugger' tab shows:

```plaintext
Main thread
 ReplyWithHeader
```

There are also tabs for Network, Style Editor, Storage, and Accessibility, but I'm not sure about those.

**Comment by jeevatkm** [comment]
@masked-shizuma For errors and debugging, we only have to look at the Console tab. So you didn't see any errors in the console tab??

For your information, I updated my TB to 128.1.1esr on the MacBook and tested v3.1.0, and it is working. I do not have Windows 10 OS.

I have prepared debug log lines for the current development version, v3.2.0. Can you try this version to see if there are any errors in the reply?
[replywithheader-v3.2.0-dev.xpi.zip](https://github.com/user-attachments/files/16734769/replywithheader-v3.2.0-dev.xpi.zip)

_Note: Extract the Zip file and install the xpi._

**Comment by masked-shizuma** [comment]
Thank you for your reply.  
After installing replywithheader-v3.2.0-dev.xpi, I performed a "reply" on a certain email.  
As a result, a lot of information was displayed in the console tab.  
Could you please tell me which parts of this information I should check?

**Comment by jeevatkm** [comment]
As you can see, there are many lines in the logs. I do not know which part might be causing an issue. 

So, I would suggest picking a few non-sensitive emails, performing a "reply" copy of all the log lines from the console tab, and sending it to my email address (you can find it on readme).

**Comment by jeevatkm** [comment]
@masked-shizuma Did you write any review comments on the Thunderbird website for RWH?

**Comment by masked-shizuma** [comment]
> @masked-shizuma Did you write any review comments on the Thunderbird website for RWH?
No, I have not posted a review about RWH.

**Comment by masked-shizuma** [comment]
I have sent the console log to your email.

**Comment by jeevatkm** [comment]
@masked-shizuma I have reviewed the console log. 

You have tried to "reply" to plain text emails based on the log. My guess is that Thunderbird is having an issue with the `splice` function on your machine.
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/a4a81fed7cb6fbf5b028357335ff7bec9d61fea2/modules/compose.mjs#L249

Can you perform "reply" on HTML emails and share the log?

**Comment by masked-shizuma** [comment]
Thank you for your reply.
I have sent the console log via email again.

**Comment by jeevatkm** [comment]
I have analyzed the given logs and prepared the next development version with logs. Can you try this version using the same plain text email you used before?
[replywithheader-v3.2.0-dev.xpi.zip](https://github.com/user-attachments/files/16738381/replywithheader-v3.2.0-dev.xpi.zip)

Can you please get me the log lines after you try plain text?

**Comment by jeevatkm** [comment]
@masked-shizuma Please ignore my previous message; I think I found a problem and applied the fix. Can you please test this version?
[replywithheader-v3.2.0-dev.xpi.zip](https://github.com/user-attachments/files/16738489/replywithheader-v3.2.0-dev.xpi.zip)

**Comment by masked-shizuma** [comment]
> @masked-shizuma Please ignore my previous message; I think I found a problem and applied the fix. Can you please test this version? [replywithheader-v3.2.0-dev.xpi.zip](https://github.com/user-attachments/files/16738489/replywithheader-v3.2.0-dev.xpi.zip)

Thank you for your reply.
After installing the replywithheader-v3.2.0-dev.xpi that you provided, I tested the 'Reply' function for both plain text and HTML emails. As a result, the reply header is now displayed in both types of emails. The replywithheader-v3.2.0-dev.xpi is working fine. The types for Thunderbird, Outlook, Simple, and Lookout are all being displayed without any issues. I appreciate your support. 
Thank you.

**Comment by jeevatkm** [comment]
@masked-shizuma Nice. It's good to hear it's started working for you. For now, please continue to use this version of the addon. I will work on making a release version.

Please provide 5-star reviews on [Thunderbird addon website](https://addons.thunderbird.net/en-US/thunderbird/addon/replywithheader/).
