### ISSUE TITLE
Locale combobox in the Add-On Settings blank by default, causes "undefined" header labels

### ISSUE THREAD

**Issue by turekv** [jeevatkm/ReplyWithHeaderMozilla#177]
I have run into the resolved issue #168 in Linux with a Czech (cs_CZ, i.e., unsupported) locale and RWH v.3.2.0. The problem stemmed from the fact that the locale combobox was blank by default, and I had to select a suitable locale for the "undefined" header labels to become "From" etc.

If no locale match is found among the supported locales, it might be a good idea to use, e.g., US English by default.

Additional information:
* OS: Linux x64
* TB: 128.1.0esr (64-bit)
* RWH: 3.2.0
* OS/TB locale: cz_CZ

**Comment by jeevatkm** [comment]
@turekv, you're correct. The correct approach is to default to English. Is it still occurring? I fixed it as part of the v3.2.0 release.
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/cffbed9d46b5da3b7efc5581d4d42588deb0d6bc/background.js#L44

I will investigate it; thanks for bringing it up.

**Comment by jeevatkm** [comment]
@turekv Thanks for your feedback. Can you please try this?

[replywithheader-v3.3.0-dev.xpi.zip](https://github.com/user-attachments/files/16809426/replywithheader-v3.3.0-dev.xpi.zip)

**Comment by jeevatkm** [comment]
@turekv Thanks for validating it; it's good to hear that the locale issue is resolved.

> I also had to change at least one thing in the settings (e.g., "12hr format" --> "24hr format"; so that the add-on preferences were stored) in order for the add-on to start doing what it was supposed to do. Until something got modified here, the default Thunderbird attribution ("On DATE, SENDER wrote:") was used.

I tried to replicate it on my Mac, but I couldn't. 
For your information, all settings are created with a default value during the new add-on installation. In the update scenario, TB preserves all add-on settings, and during the add-on's uninstall, TB removes all the settings.

> Incidentally, I noticed a typo in the top-left combobox ("Select AN Identities" -- highlighted in the attached screenshot as well).

Typically, TB could have "N" of mail identity in the Mail Accounts. By default, all Identities are enabled; if users want to disable RWH on a particular identity, they can uncheck it from the "Select an Identities" dropdown.

If I misunderstood anything, please let me know.

**Comment by jeevatkm** [comment]
@turekv Thanks for the details. 

* I will continue investigating the root cause of the first install not working OOTB. After looking at the screenshot, I'm wondering where it could be failing; quick thoughts are - (I will create a new issue)
   - First, install not working with already supported Locale
   - First, install not working with un-supported Locale
* Now I understand I will correct it as "Select Identities" (I will update it as part of current issue)

**Comment by jeevatkm** [comment]
@turekv I'm wondering, is it possible to write 5-star review here? https://addons.thunderbird.net/en-US/thunderbird/addon/replywithheader/

**Comment by jeevatkm** [comment]
Ohh, Thank you @turekv.
