### ISSUE TITLE
Take care Quoted Shifting in the email

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeaderMozilla#18]
Hi Jeeva,

This is Rudolf from Slovakia. I am using TB (38.6.0) for a years. Few years ago, due to compatibility with most of colleagues who are working with Outlook, I started to use few Add-ons (SmartTemplate4 and QuoteAndComposeManager) - they work well, however I have still an issue with them.

Any email I am replying to, TB adds kind of quote character (>) - however this hiding is not visible in TB itself, however when I see my reply in Outlook, there is kind of shifting of quoted text below header. 

One quick way to detect this is to - Reply email in TB, but not send it, then select replied email with header and paste it into text editor. You will see:

[Removed header info here due personal info]

```
> Hello Rudolf,
>
> 
>
> I have checked bla bla...
> 
>
```

This quota border characters ">" are not visible in TB, but they are actually sent - most likely via html code "blockquote" ...

Would it be possible, please, to improve your nice addon to really remove the quoted "shifting" ? I can send you email as an example and also screenshots how it looks in outlook

Thank you so much
Regards
Rudolf

**Comment by cnmicha** [comment]
I can confirm this issue.

Additionally, I observed that the quote border characters are not removed in the plain text part of and email that consists of a HTML and a plain text version. Maybe this is related.

**Comment by cnmicha** [comment]
@jeevatkm Do you have a timeline to fix this?

**Comment by cnmicha** [comment]
A workaround is to install the ReFwdFormatter plugin (https://addons.thunderbird.net/en-US/thunderbird/addon/refwdformatter/) additionally to ReplyWithHeader. It automatically removes the shift to the right in the original message.

**Comment by jeevatkm** [comment]
Closing it in favor of the v3 version, https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
