### ISSUE TITLE
Subject, Date, From, To show as "undefined"

### ISSUE THREAD

**Issue by guestrinh** [jeevatkm/ReplyWithHeaderMozilla#180]
Excellent extension!!!
I have just installed the latest version (3.2.0) and I have the following issue when replying:

undefined ‘Phenomenal’ tool sequences DNA and tracks proteins — without cracking cells open
undefined Friday, October 11, 2024 at 1:52 p.m. EDT
undefined Nature Briefing <briefing@nature.com>
undefined xxxx@xxxx.com

Windows 10
Thunderbird Version 128.3.1esr | Released October 10, 2024

Thank you!

**Comment by jeevatkm** [comment]
@guestrinh, thanks for reaching out.

Can you follow these steps and share the details while performing reply & forwarding?

Steps to reach the debug console log:

- Go to Add-ons Manager 
- click Settings wheel icon 
- click Debug Add-ons 
- find the ReplyWithHeader add-on 
- click Inspect button
- now debug console window appears

**Comment by guestrinh** [comment]
Hi @jeevatkm,
I have the debug console open. What should I do next?

**Comment by jeevatkm** [comment]
Perform reply and forward then copy all the lines from the console window logs and share it with me.

**Comment by guestrinh** [comment]
![image](https://github.com/user-attachments/assets/38425266-1bdf-42d4-b1ba-6d487fd91c5c)

**Comment by jeevatkm** [comment]
Screenshot did not have the info I'm looking for.
I will prepare the debug add on version for you tonight.
Also may I know your thunderbird locale you're using?

**Comment by guestrinh** [comment]
![image](https://github.com/user-attachments/assets/f89b8aa7-ccb6-45b7-8531-205585669a47)

**Comment by guestrinh** [comment]
Date and Time Formatting
Application locale: English (Canada)
Regional settings locale: English (Canada) (Selected)

**Comment by jeevatkm** [comment]
@guestrinh, The last screenshot of the options helped me to understand the issue. Can you please try this upcoming 3.3.0-dev version?
[replywithheader-v3.3.0-dev.xpi.zip](https://github.com/user-attachments/files/17348910/replywithheader-v3.3.0-dev.xpi.zip)

_PS: Kindly extract the zip and install the `.xpi` file._

**Comment by jeevatkm** [comment]
@guestrinh, did you get a chance to try it?

**Comment by guestrinh** [comment]
The issue was solved! Thank you @jeevatkm !!!
What was the cause?

**Comment by guestrinh** [comment]
I found the cause in the developer console. Thanks!

**Comment by jeevatkm** [comment]
It was a locale selection issue. Thanks for your confirmation.

**Comment by jeevatkm** [comment]
Fixed as part of #177
