### ISSUE TITLE
TB ver. 45.1.0 forward issue

### ISSUE THREAD

**Issue by mariobig** [jeevatkm/ReplyWithHeaderMozilla#19]
Hi,

RWH plugin doesn't work properly with new version of Thunderbird v45.1.0. It doesn't attach header to forwarded mails. It works properly with replies.

**Comment by jeevatkm** [comment]
Thanks, I will have a look after work.

**Comment by mariobig** [comment]
Many thanks.

Mariusz


wawaSOFT
	wawaSOFT INFO ,
mobile: +48 601 606 941
email: info@wawasoft.com
web: pl.wawasoft.com <http://pl.wawasoft.com>


Ta wiadomość została podpisana cyfrowo zgodnie ze standardem S/MIME. 
Tożsamość autora potwierdzona jest cyfrowym certyfikatem wystawionym 
przez zaufany urząd certyfikacji.
This message has been signed digitally in compliance with S/MIME 
standard. Identity of the author is confirmed by the digital certificate 
issued by trusted certification authority.
------------------------------------------------------------------------

------------------------------------------------------------------------
*From:* Jeevanandam M. <notifications@github.com>
*Sent:* Monday, May 16, 2016 22:32:47 GMT+0200
*To:* jeevatkm/ReplyWithHeaderMozilla 
<ReplyWithHeaderMozilla@noreply.github.com>
*Cc:* mariobig <info@wawasoft.com>, Author <author@noreply.github.com>
*Subject:* [jeevatkm/ReplyWithHeaderMozilla] TB ver. 54.1.0 forward 
issue (#19)

**Comment by jeevatkm** [comment]
I have just installed `45.1.0` on my macbook pro and installed RWH v1.3. It seems to working. I need your help to nail down the forward problem. Can you please provide additional information?

Enabling debug mode in v1.3 (in v1.4 it will be handy via About tab in the add-on preferences)
* `Preferences -> Advanced Tab -> click Config Editor`
* Click `I'll be careful, I promise!` button
* Look for `extensions.replywithheader.debug` and double click
* Value will become `true`
* click `Tools -> Error Console`

Please provide error info from console (warn and info you can ignore it).

**Comment by jeevatkm** [comment]
If you don't mind, can you please try this RWH v1.4-beta and share your feedback?

http://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v1.4-beta.xpi

**Comment by mariobig** [comment]
1. Following your instruction I am attaching printscreen with detected error:
![error_rwh](https://cloud.githubusercontent.com/assets/15660503/15351230/912395b4-1cde-11e6-9439-7bb65aeccf88.jpg)

2. I installed RWHv1.4-beta you published today and TB works correctly. See printscreen:
![frwd_after](https://cloud.githubusercontent.com/assets/15660503/15351593/46e5b048-1ce0-11e6-93fc-e2163a484863.jpg)


3. Before the latest extension installation header looked as follows:
![frwd_before](https://cloud.githubusercontent.com/assets/15660503/15351598/53a13a78-1ce0-11e6-8141-bce847da96c3.jpg)


4. Please be aware that the extension you sent me on February was version v1.4-beta so, the current one should be later version.

**Comment by mariobig** [comment]
I was too quick. RWH extension still doesn't work properly. It randomly attach original or redefined header. It happens in case of forwarded mails only. In addition it removes signature in some cases. It occurs in almost all mails created in TB and then forwarded somewhere else.

**Comment by jeevatkm** [comment]
Yes, I have updated the v1.4-beta after February. That's why I have shared latest one.

Thanks for sharing error info, I will have a look. Also could you please guide me to replicate the issue for "It occurs in almost all mails created in TB and then forwarded somewhere else." so I can address it before the release.

**Comment by jeevatkm** [comment]
@mariobig - I have addressed the issue you have pointed out via screenshot. Can you please download it again and verify it?

**Comment by jeevatkm** [comment]
@mariobig - did you get a chance verify?
