### ISSUE TITLE
Locale date abbr 

### ISSUE THREAD

**Issue by surph** [jeevatkm/ReplyWithHeaderMozilla#22]
excellent work!!

there is bug when selecting Header date format >Locale date format; the abbreviation for zone appears  wrong.
in my case instead of PKT it is showing PST
Please fix

Thanks

**Comment by jeevatkm** [comment]
Sure I will have a look. Thanks for reporting.

Can you please post sample?

**Comment by jeevatkm** [comment]
@surph As I'm working on to add support for latest thunderbird release. I have verified the code. I'm not doing explicit timezone name compose. 

I need your help diagnose the issue.

**Comment by jeevatkm** [comment]
@surph Closing it. Please open new/reopen it more debug info. Thank you.
