### ISSUE TITLE
Reply not showing signature in RWH 1.5  in Postbox 5.0.14

### ISSUE THREAD

**Issue by sean-newman** [jeevatkm/ReplyWithHeaderMozilla#25]
Hi Jeevanandam,

First up - thanks for doing this add-on. I'm trying to ditch Outlook on my Mac but need to keep the standard look and feel in replies and conversations with the rest of the company - RWH is so close to getting me there!

I'm using RWH 1.5 in PostBox 5.0.14, and I need to have my email signature above the previous emails. This is not working when I hit Reply or Reply All.

The signature does appear correctly when I hit Forward, but it also has the "-------- Original Message --------" line directly under the signature and before the previous emails.

Let me know if you want more diagnostic info or if you want me to test a new release - happy to assist.

Regards,

Sean

**Comment by jeevatkm** [comment]
@sean-newman I will analyze and get back to you. Sure, I will take your help during a testing.

**Comment by jeevatkm** [comment]
@sean-newman Sorry for the late response. I got occupied with my [aah framework v0.6 release](https://aahframework.org)

I have downloaded the Postbox v5.0.14 and tested with RWH `v1.5`. It is working as expected.

Added new signature and Only settings I did is: 

Preferences -> Accounts -> (select your email account) -> Composition -> `place my signature below the reply (above the quote)`

<img width="379" alt="screen shot 2017-06-07 at 12 21 03 pm" src="https://user-images.githubusercontent.com/1175977/26897076-fb1165d8-4b7b-11e7-941f-7f047d86c5fa.png">


_PS: RWH doesn't support Postbox quick reply option. I'm sorry_

**Comment by sean-newman** [comment]
@jeevatkm: That's strange - you're using the same versions as me but mine doesn't show the signature at all for Reply and Reply All, and shows the signature plus the ---original message--- straight after it.

Here are the screens for my settings both in Postbox and in RWH:

_Postbox_
Preferences -> Accounts -> Exchange Account -> Composition

![image](https://user-images.githubusercontent.com/28945427/26907627-3c2d4b06-4c38-11e7-89db-ed4ca1162806.png)

_RWH_

![image](https://user-images.githubusercontent.com/28945427/26907643-55c3f236-4c38-11e7-990c-89289e7ce948.png)

I've enabled debug mode - is there a log file I can send you?

**Comment by jeevatkm** [comment]
@sean-newman Postbox doesn't provide log file. however it has error console where all the log comes in (press Command+Shift+J to open).

Are you okay with remote Screen Share session, so that you can show your screen with the issue and I will show my postbox? This way we can find differences and address it.

I'm in PDT time zone, please let me know your answer.

**Comment by sean-newman** [comment]
@jeevatkm: I'm happy to do a Screen Share session. We can do Skype if you want to talk as well.

I'm in AEST. Let me know how we can exchange details.

**Comment by jeevatkm** [comment]
I'm fine with Skype call and screen share let's move our conversation into my email id "jeeva at myjeeva dot com"
