### ISSUE TITLE
How can I help to translate for portugueze brazilian

### ISSUE THREAD

**Issue by wanderleihuttel** [jeevatkm/ReplyWithHeaderMozilla#26]
Hello, how can I help to translate for portugueze brazilian?

Best Regards
Wanderlei

**Comment by jeevatkm** [comment]
@wanderleihuttel Thank you for your interest.

Currently RWH not implemented with localization (supports only english). Not sure how much effort it would take.

Feel free to give it try and let me know, I'm happy assist you anytime.

**Comment by ofa-** [comment]
see e.g. #31 for a basic i18n / translation support proposal.

**Comment by jeevatkm** [comment]
@wanderleihuttel Hope you're doing well. Can you please have a look on [this comment](https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/12#issuecomment-364220581) and provide translation?

**Comment by jeevatkm** [comment]
@wanderleihuttel moving it to enhancement, since @ofa- have already implemented the feature.

Going forward, its gonna be adding below set of translation values into RWH.

```
From:
To:
Cc:
Subject:
Date:
Sent:

Forwarded Message
Original Message
```

**Comment by jeevatkm** [comment]
@wanderleihuttel I have prepared the `v2.1.0.beta.1` with Brazil locale, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by jeevatkm** [comment]
`pt-BR` locale added, I'm closing it 😄

**Comment by wanderleihuttel** [comment]
Hello @jeevatkm! I've just seen the message today! I've installed the beta version and the option to choose another language is showed, but when I've opened the .xpi file I couldn't find any locale file for translate for Portuguese Brazilian.

**Comment by ofa-** [comment]
@wanderleihuttel the localisation is "home-made", not using the usual system;  it's all in a single file:
https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/master/chrome/content/i18n.js
