### ISSUE TITLE
Body of email when reply

### ISSUE THREAD

**Issue by tinazizel** [jeevatkm/ReplyWithHeaderMozilla#28]
Hello!
Thank you for this great add on! I have noticed that when replying to an email, the body of the initial email sent to me is moved slightly to the right, as if I have chosen the Tab button (in word) for the whole email. This is not the case when forwarding an email. Moreover, the 2 "--" before my signature disappear.
![email2](https://user-images.githubusercontent.com/33460540/32507351-db5b7ee4-c3ef-11e7-9c0b-826af21cdc43.jpg)
![email](https://user-images.githubusercontent.com/33460540/32507352-db97e0fa-c3ef-11e7-9190-d67327a284bb.jpg)

Thanks!

**Comment by jeevatkm** [comment]
@tinazizel Sorry for late reply. Thank you for your compliment.

Not to worry. There are improvements happened in the RWH add-on.

Please try RWH v2.0-beta and share your feedback.
https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi

**Comment by jeevatkm** [comment]
@ofa- may I ask your help on investigating this issue? I did long time ago couldn't find a lead.

**Comment by jeevatkm** [comment]
@tinazizel I have prepared the `v2.1.0.beta.1`, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by jeevatkm** [comment]
I'm closing it.
