### ISSUE TITLE
Replied/forwarder content is always plain text

### ISSUE THREAD

**Issue by wikiaal** [jeevatkm/ReplyWithHeaderMozilla#29]
Replied/forwarded content looses its original format and is converted always to plain text.

**Comment by jeevatkm** [comment]
@wikiaal Thanks for reporting an issue. I have responded on Disqus and add-on portal. 

Could you please share following information?

* Thunderbird version you're using
* RWH add-on debug log
     * First enable the debug log via add-on preferences on `About `Tab - Check `Enable debug mode`
     * Then open `Error Console` window by pressing `Shift + Command + J`
     * Now do both `Reply and Forward` behavior on the emails you have an issue
     * Share all the debug line starts with `RWH` from the error console window

**Comment by jeevatkm** [comment]
And also Mail account type info, such Gmail, Outlook/Exchange, etc.

**Comment by wikiaal** [comment]
My mail accont is GMail but the issue occurs with any type of mail account that sent the mail (GMail, Outlook, Live, etc.).

This is code for a Reply to an email in Error Console:

RWH   DEBUG	Initializing
RWH   DEBUG	Is HTML compose: true
RWH   DEBUG	Reply/ReplyAll mode
RWH   DEBUG	signatue in the bottom
RWH   DEBUG	reached blockquote, so no signature
RWH   DEBUG	Message URI: imap-message://andrea.a.locatelli%40gmail.com@imap.gmail.com/INBOX#9519
RWH   DEBUG	Locale date format
RWH   DEBUG	
From: Luca Moretti
To: Andrea Locatelli
CC: 
Subject: Windows Update issue KB4054517
Date: Wednesday, Jan 3, 2018 11:16 E
RWH   DEBUG	Font face: Tahoma	Font size: 13	Color: #000000
RWH   DEBUG	Header HTML: <div id="rwhMsgHeader"><br /><hr id="rwhMsgHdrDivider" style="border:0;border-top:1px solid #B5C4DF;padding:0;margin:10px 0 5px 0;width:100%;"><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>From:</b> Luca Moretti</font></span><br/><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>Sent:</b> Wednesday, Jan 3, 2018 11:16 E</font></span><br/><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>To:</b> Andrea Locatelli</font></span><br/><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>Subject:</b> Windows Update issue KB4054517</font></span><br/><br /></div>

This is code for a Forward to an email  Error Console:

RWH   DEBUG	Initializing
RWH   DEBUG	Is HTML compose: true
RWH   DEBUG	Forward mode
RWH   DEBUG	Message URI: imap-message://andrea.a.locatelli%40gmail.com@imap.gmail.com/INBOX#9519
RWH   DEBUG	Locale date format
RWH   DEBUG	
From: Luca Moretti
To: Andrea Locatelli
CC: 
Subject: Windows Update issue KB4054517
Date: Wednesday, Jan 3, 2018 11:16 E
RWH   DEBUG	Font face: Tahoma	Font size: 13	Color: #000000
RWH   DEBUG	Header HTML: <div id="rwhMsgHeader"><br /><hr id="rwhMsgHdrDivider" style="border:0;border-top:1px solid #B5C4DF;padding:0;margin:10px 0 5px 0;width:100%;"><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>From:</b> Luca Moretti</font></span><br/><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>Sent:</b> Wednesday, Jan 3, 2018 11:16 E</font></span><br/><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>To:</b> Andrea Locatelli</font></span><br/><span style="margin: -1.3px 0 0 0 !important;"><font face="Tahoma" color="#000000" style="font: 13px Tahoma !important; color: #000000 !important;"><b>Subject:</b> Windows Update issue KB4054517</font></span><br/><br /></div>
RWH   DEBUG	signatue in the bottom
RWH   DEBUG	isSignature: false
RWH   DEBUG	sigNode: undefined

Kind regrads
Andrea

**Comment by wikiaal** [comment]
Result is that, despite the fact that replied/forwarded mails are HTML, the content is always plain text.

**Comment by wikiaal** [comment]
In my case, to activate Mozilla Error Console, the right way is CTRL + SHIFT + J

**Comment by jeevatkm** [comment]
@wikiaal You're right, on windows this is correct way to bring error console.

> In my case, to activate Mozilla Error Console, the right way is CTRL + SHIFT + J

What is your thunderbird version? 

I will analyze and get back to you. Thanks for sharing debug information.

**Comment by wikiaal** [comment]
@jeevatkm I'm using Thunderbird 52.5.2 on Windows 10 x64 1709

**Comment by wikiaal** [comment]
Mmm... really odd behavior... for example, replying to your notification email received from GitHub doesn't convert replied content to plain text.

![cattura](https://user-images.githubusercontent.com/35070730/34552564-765ce978-f122-11e7-96e6-6783927950df.PNG)

**Comment by wikiaal** [comment]
In some case, behavior is different between Reply (HTML) and Forward (plain text)

![cattura](https://user-images.githubusercontent.com/35070730/34553057-b5a642f2-f125-11e7-9149-34efa1f88397.PNG)

**Comment by jeevatkm** [comment]
@wikiaal Typically RWH add-on composes the mail headers based on mail type such as HTML or Plain text.

As in thunderbird, if you hold `shift` key and do reply/forward it will always compose plain text regardless. RWH add-on respects that.

In your case I need to do homework at my end first then I will get back. My best guess is mostly its related to your thunderbird settings that causes add-on some interferences.

**Comment by wikiaal** [comment]
![cattura](https://user-images.githubusercontent.com/35070730/34553525-3bac2fae-f128-11e7-93af-0a0c5bc9286f.PNG)

**Comment by jeevatkm** [comment]
@wikiaal Could you please try RWH v2.0-beta and share your feedback?

https://docs.myjeeva.com/rwh-moziila/replywithheader@myjeeva.com-v2.0-beta.xpi

**Comment by wikiaal** [comment]
Hmmm... at link https://docs.myjeeva.com/rwh-moziila/replywithheader@myjeeva.com-v2.0-beta.xpi
    I receive a 404 Not Found error.
    
      
        From: Jeevanandam M.
        Sent:
            Sunday, Feb 18, 2018 3:01 E
        To:
            jeevatkm/ReplyWithHeaderMozilla
        Cc:
            wikiaal; Mention
        Subject:
            [jeevatkm/ReplyWithHeaderMozilla] Replied/forwarder content
            is always plain text (#29)
        
      
    
    
      @wikiaal Could you please try RWH
        v2.0-beta and share your feedback?
      https://docs.myjeeva.com/rwh-moziila/replywithheader@myjeeva.com-v2.0-beta.xpi
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jeevatkm/ReplyWithHeaderMozilla","title":"jeevatkm/ReplyWithHeaderMozilla","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jeevatkm/ReplyWithHeaderMozilla"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jeevatkm in #29: @wikiaal Could you please try RWH v2.0-beta and share your feedback?\r\n\r\nhttps://docs.myjeeva.com/rwh-moziila/replywithheader@myjeeva.com-v2.0-beta.xpi "}],"action":{"name":"View Issue","url":"https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/29#issuecomment-366486554"}}}

**Comment by jeevatkm** [comment]
@wikiaal It seems I made a typo in the URL.
https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi

**Comment by wikiaal** [comment]
Installed ReplyWithHeader
        2.0 beta: I do not see improvements if compared to 1.5. I get the same unpredictability in
                  text formatting (sometimes html, sometimes plain) when
                  I reply / forward mail
                  messages. I'm using
                  Thunderbird 52.6.0.
                    
                    Kind regards
                      Andrea Locatelli
              
      
    
      
        From: Jeevanandam M.
        Sent:
            Sunday, Feb 18, 2018 17:59 E
        To:
            jeevatkm/ReplyWithHeaderMozilla
        Cc:
            wikiaal; Mention
        Subject:
            [jeevatkm/ReplyWithHeaderMozilla] Replied/forwarder content
            is always plain text (#29)
        
      
    
    
      @wikiaal It seems I made a typo in
        the URL.
        https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jeevatkm/ReplyWithHeaderMozilla","title":"jeevatkm/ReplyWithHeaderMozilla","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jeevatkm/ReplyWithHeaderMozilla"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jeevatkm in #29: @wikiaal It seems I made a typo in the URL.\r\nhttps://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi"}],"action":{"name":"View Issue","url":"https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/29#issuecomment-366529932"}}}

**Comment by jeevatkm** [comment]
@wikiaal Its an internal improvements, new feature, etc. Also `v2.0-beta` debug log is more informative in-terms of flow, handling, etc.

I'm sure you have some unique issue. Its good to address that. 

**It would be best to have screen share session tomorrow for debugging and analyzing. I'm in `PST` time zone, let me know the time; we can have the session.** 

_PS: During a debugging please use English version of Thunderbird, so that I can read/see the mail settings which you're using._

**Comment by wikiaal** [comment]
@jeevatkm Okay, we can arrange a screen share session (I have TeamViewer installed). My time zone is +9 hours (CET - Central European Time) far from yours, so we could schedule it between 9:00 am and 11:00 am (PST - Pacific Standard Time) which is between 6:00 pm and 8:00 pm for me (CET). I'll provide to install Thunderbird EN-US to let you to have settings in English.

Kind regards
Andrea

**Comment by jeevatkm** [comment]
@wikiaal Between 9:00 am and 11:00 am (PST) Sounds good. I will ping you on this thread once I get up in the morning. Also I will install TeamViewer.

**Comment by wikiaal** [comment]
@jeevatkm Okay between 9:00 am and 11:00 am (PST). I'll wait for your ping on this thread. Andrea

**Comment by jeevatkm** [comment]
@wikiaal I'm ready and I have installed TeamViewer too.

**Comment by jeevatkm** [comment]
Also what is your choice of messaging/chat, so we can jump onto?

**Comment by wikiaal** [comment]
@jeevatk I'm coming: 3-4 minutes and I'm ready.

**Comment by jeevatkm** [comment]
@wikiaal Okay, thanks.

**Comment by wikiaal** [comment]
Tried to install en-US version of Thunderbird but menu language continue to be Italian.

**Comment by jeevatkm** [comment]
That is okay. I will take your help. Any chat app we can use for message/audio?

**Comment by wikiaal** [comment]
TeamViewer
ID: 613466211
Pwd: 9509

Please be careful, because my andrea.a.locatelli@gmail is my private and job mail account.

**Comment by wikiaal** [comment]
Thunderbird is open, if you want to communicate, please, open a a text file on the desktop and write.

**Comment by jeevatkm** [comment]
@wikiaal understood. I have deleted your post just now.

**Comment by wikiaal** [comment]
ok, you have control of my computer

**Comment by jeevatkm** [comment]
@wikiaal thanks for your time for debugging. 

After analysis:
- It seems Thunderbird unable to determine the email type properly for some emails.
- It could be related to sender email client or mail server or thunderbird itself

RWH add-on gets the email information from thunderbird and acts upon it. So add-on is working fine.

**Comment by jeevatkm** [comment]
@wikiaal We haven't tried this option. Can you turn off this option (available under Tools -> Account Settings -> Email Account)?
<img width="263" alt="screen shot 2018-02-19 at 1 24 11 pm" src="https://user-images.githubusercontent.com/1175977/36397607-4e8433c8-1578-11e8-95ac-5711a26b83aa.png">

and then try Reply & Forward. See how it behaves?

**Comment by wikiaal** [comment]
If I correctly understood your request, here the result:

![screenshot1](https://user-images.githubusercontent.com/35070730/36406685-ddd3b7b2-15f8-11e8-9a96-aa1e381343db.PNG)
![screenshot2](https://user-images.githubusercontent.com/35070730/36406689-e13d40f8-15f8-11e8-8c35-7f77e101ae16.PNG)

**Comment by jeevatkm** [comment]
@wikiaal Yes, you understood correctly. Thanks for sharing the result.

So our morning conclusion stays correct. This setting is not helpful too.
