### ISSUE TITLE
Add per-account header language auto selection

### ISSUE THREAD

**Issue by ofa-** [jeevatkm/ReplyWithHeaderMozilla#44]
Enhancement: automatically select the header language/locale based on sending account email
=> PR #50

**Comment by ofa-** [comment]
additional locale "automation" support for #12

**Comment by ofa-** [comment]
See PR#50

**Comment by ofa-** [comment]
@jeevatkm you can **delete** this issue, it is covered by #50

**Comment by jeevatkm** [comment]
Merged into master 😄

**Comment by ofa-** [comment]
@jeevatkm can you try to **delete** this issue, just to see if it goes away from the list in #12 ... 
(and it's a dup)

**Comment by jeevatkm** [comment]
Actually in GitHub, there is no delete option 🤣 That list generated by auto reference if you mention `#50` to any PR or Issue

**Comment by ofa-** [comment]
@jeevatkm ok, too bad.  I hope github team proved the issue delete functionality some day.

I delete my old/no-longer relevant comments and cleanup the issues threads.

**Comment by ofa-** [comment]
@jeevatkm you may as well do the same :-)

**Comment by jeevatkm** [comment]
@ofa- Typically this how it works.

* First we create an issue to propose or plan feature/enhancement, etc.
* then we implement that then create a PR mentioning `implementation of #so-and-so` to refer that issue.

I hope it makes sense.

**Comment by ofa-** [comment]
yeah I know the process.  They even have a nice cross-close feature i.e. when you say `closes #XX` in the PR, it automatically closes the mother issue.  However once the PR works [and describes the feature better than the original issue], I still think it would be better to simply remove the [now] dup.

Plus closed issues are RED whereas merged pull requests are PURPLE.
