### ISSUE TITLE
Target RWH v2.0 release for Thunderbird 60

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeaderMozilla#62]
Doc reference for add-on changes: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

TB 60.* brings lots of breaking changes.

Start working on it 😄

**Comment by jeevatkm** [comment]
v2.0 beta updates as of May 1, 2018 => 
http://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi

**Comment by jeevatkm** [comment]
v2.0 beta updates as of May 9, 2018
https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi

**Comment by jeevatkm** [comment]
v2.0 beta updates as of May 17, 2018
https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi

Same build going to be released on AMO as beta version soon.

**Comment by jeevatkm** [comment]
v2.0 beta updates as of May 25, 2018
https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi

**Comment by n8v8R** [comment]
To my humble understanding there will be changes to Add-ons from TB 60 to TB 62 which not be covered in the guide cited at the start of this thread. Came across a few Add-ons that worked in 60 but not in 62.

**Comment by n8v8R** [comment]
Sure, can do for TB 60, if that would be of interest?

But I since TB 60 became available as x64 for Win I removed TB Daily (current 62) since it broke too many add-ons.

**Comment by jeevatkm** [comment]
I was interested to get feedback for TB 62 and its errors. It's okay thank you @n8v8R

**Comment by jeevatkm** [comment]
@n8v8R I have tried TB 61 to 63, they not even recognizing the add-ons. No documentations around :(

**Comment by n8v8R** [comment]
https://github.com/micz/ThunderStats/issues/162

**Comment by jeevatkm** [comment]
RWH add-on v2.0 submitted to AMO. Closing it.
