### ISSUE TITLE
allow to define font size in pt

### ISSUE THREAD

**Issue by zyro23** [jeevatkm/ReplyWithHeaderMozilla#63]
currently, the font size for the reply header can only be set in `px`. would be great if `pt` is supported, too.

**Comment by jeevatkm** [comment]
@zyro23 Okay, will add it in the v2.0 release 😄

**Comment by zyro23** [comment]
awesome! thank you :)

**Comment by jeevatkm** [comment]
Point option add in to v2.0 beta

You can download it from here https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/62#issuecomment-392241327
