### ISSUE TITLE
Where can I download ReplyWithHeader 2.0beta for Thunderbird 60.0?

### ISSUE THREAD

**Issue by wikiaal** [jeevatkm/ReplyWithHeaderMozilla#65]
I'm going to install Thunderbird 60 x64 and would like to know where I can download ReplyWithHeader 2.0beta version to test if it works.

Kind regards
Andrea

**Comment by jeevatkm** [comment]
@wikiaal download link is in this thread https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/62#issuecomment-392241327

Is TB 60 released?

**Comment by wikiaal** [comment]
Yes, Thunderbird 60 x32 and x64 has been released in all languages. You can
fond it in FTP Mozilla site.

Il mar 7 ago 2018, 07:13 Jeevanandam M. <notifications@github.com> ha
scritto:

**Comment by jeevatkm** [comment]
@wikiaal Thank you. I will start the work for making v2.0 release.
