### ISSUE TITLE
Cannot download ReplyWithHeader v2.0 beta

### ISSUE THREAD

**Issue by wikiaal** [jeevatkm/ReplyWithHeaderMozilla#66]
Sorry, but cannot download ReplyWithHeader v2.0 beta update from its link
https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.0-beta.xpi

It says that file is damaged.

Kind regards
Andrea

**Comment by jeevatkm** [comment]
Is TB saying file is corrupted?

**Comment by jeevatkm** [comment]
Let me download TB 60 and try at my end.

**Comment by jeevatkm** [comment]
I have tried it, its working. I have created a Zip archive for you and attached to the comment. Please try.

[replywithheader@myjeeva.com-v2.0-beta.xpi.zip](https://github.com/jeevatkm/ReplyWithHeaderMozilla/files/2268850/replywithheader.myjeeva.com-v2.0-beta.xpi.zip)

**Comment by wikiaal** [comment]
Now it works (using Firefox browser), many thank for your kind and prompt reply.

**Comment by jeevatkm** [comment]
You're welcome @wikiaal. Please share your feedback. Before release I can address if any issues.
