### ISSUE TITLE
Issue with reply / forward with Thunderbird 60.0 x64 installed from scratch

### ISSUE THREAD

**Issue by wikiaal** [jeevatkm/ReplyWithHeaderMozilla#68]
With Thunderbird 60.0 x64 installed as an upgrade from Thunderbird 52.9.1 x32, ReplyWithHeader seems to work well.

With Thunderbird 60.0 x64 installed from scratch there is an issue in replying / forwarding emails: vertical distance from (replyed / forwarded email) header has different number of empty lines to the top.

**Comment by jeevatkm** [comment]
@wikiaal Are you seeing this behavior on v2.0?

I have already submitted add-on for review, it is in the queue. For now I will analyze the issue.

**Comment by wikiaal** [comment]
I'm seeing the issue with 2.0beta. I have different Thunderbird installations: in the ones migrated from 52.9.1 x32 to 60.0 x64, ReplyWithHeader 2.0beta seems to work well. In the one with Thunderbird 60.0 x64 installed from scratch vertical distance from (replyed / forwarded email) header has different number of empty lines to the top (1 line for replied, 3-4 lines for forwarded).

**Comment by jeevatkm** [comment]
Closing it, many improvements happened in the TB; please open a new one for the issue. Thanks
