### ISSUE TITLE
Thunderbird 64.0b1 states addon incompatible even though install.rdf looks OK

### ISSUE THREAD

**Issue by boatbodger** [jeevatkm/ReplyWithHeaderMozilla#70]
I unzipped replywithheader-2.0-tb-windows.xpi and checked the install.rdf file.
This contains the line:
        \<em:maxVersion>64.*</em:maxVersion>

so I would expect it to run OK with 64.0b1.
I tried changing it to 64.0* - no different
Any ideas what I can try next?

**Comment by boatbodger** [comment]
I unzipped replywithheader-2.0-tb-windows.xpi and checked the install.rdf file.
This contains the line:
        <em:maxVersion>64.*</em:maxVersion>
so I would expect it to run OK with 64.0b1.
I tried changing it to 64.0* - no different
Any ideas what I can try next?

**Comment by jeevatkm** [comment]
Since TB 68.0 is released, I will be focusing on adding support for it. In-favor of #88, I'm closing this one. Thanks!
