### ISSUE TITLE
Fail to work if Timezone Abbr. is not alpha

### ISSUE THREAD

**Issue by baykant** [jeevatkm/ReplyWithHeaderMozilla#71]
If the timezone abbrv. is not alpha (eg: "+03", Turkish timezone without DST) extension fails. Change the date/time format to GMT solves the issue.
console output: 
> TypeError: tzAbbr[1].match(...) is null[Learn More]  rwh.js:215:16
	tzAbbr chrome://replywithheader/content/rwh.js:215:16

**Comment by jeevatkm** [comment]
@baykant Thanks for reporting it. I know timezone handling needs improvement. Will do in the next release.

**Comment by jeevatkm** [comment]
@baykant @johanponken I have prepared the `v2.1.0.beta.1` with date fixes, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by jeevatkm** [comment]
@johanponken After your try out, please update your review on AMO would be helpful.

**Comment by johanponken** [comment]
TB 60.5.0 (32b) OK:

• I get, for my CET locale, correctly e.g. "Thursday, February 7, 2019, 05:23 UTC+1".

• And trying also an **old summertime** mail, with header (praise be to Toggle Headers) saying:
 "Mon, 18 Jun 2018 22:08:55 +0000 (UTC)",  I get:
 "Tuesday, June 19, 2018, 00:08 UTC+2" with timezone* checked
 "Monday, June 18, 2018, 22:08 UTC" with timezone* un-checked

*Found "Include short timezone info" under "Header date format" in tab "Manage Headers" in Options. Nice and clear.

![replywithheadermozilla options scr 190209 1107](https://user-images.githubusercontent.com/39563114/52519763-dc899f00-2c60-11e9-94fc-85604dd65ca5.png)

**Comment by jeevatkm** [comment]
@johanponken Thanks for your try out and feedback. Also AMO review update 😄
