### ISSUE TITLE
Locale Error

### ISSUE THREAD

**Issue by defrilitus** [jeevatkm/ReplyWithHeaderMozilla#72]
This is indeed an excellent plug-in, but it contains a locale error.
In Apple Mail, when I choose the “English” date format in RWH (version 6.0), it comes out as “November 5, 2018 at 3:20:27 PM EST”. However, this is not English, but American (en-US).
All other major countries that employ English as a major language (e.g., UK, Ireland, Canada, Australia, New Zealand, South Africa) use the en-GB standard, thus “5 November 2018 15:20:27 -0500" or “5 Nov 2018 15:20:27 -0500".
Do you think that you can include the en-GB format in addition to the en-US one?
Thanks in advance!

PS:
In Thunderbird (RWH 1.5), where the extension is supposed to use the system settings, the date still uses the American format, even though my system locale is English - UK.

**Comment by jeevatkm** [comment]
@defrilitus Thanks for reporting an issue. I will have a look.

**Comment by jeevatkm** [comment]
@defrilitus Did you tried RWH v2.0 plugin?

**Comment by defrilitus** [comment]
@jeevatkm Nope, because I'm using TB 52.9.1 (I refuse to upgrade to 60) and RWH 2.0 is only compatible with TB 60+.

**Comment by jeevatkm** [comment]
@defrilitus I have prepared the `v2.1.0.beta.1` with locale fix `en-GB` added, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by defrilitus** [comment]
@jeevatkm I'm afraid that I no longer use Thunderbird.  If you have a beta version for Apple Mail, I would be happy to try it out.

**Comment by jeevatkm** [comment]
@defrilitus Okay, thanks for the response. Will let you know.
