### ISSUE TITLE
ReplyWithHeader 2.0+TB 60.3.1 on Mac OS X 10.11.6 Gmail account reply content is empty 

### ISSUE THREAD

**Issue by wanyixue** [jeevatkm/ReplyWithHeaderMozilla#73]
I installed ReplyWithHeader 2.0 with TB 60.3.1 on Mac OS X 10.11.6. The reply content for Gmail account is empty whereas the forward fucntion for Gamil accout and the reply/forward function for other mail accouts are OK.
<img width="1088" alt="default" src="https://user-images.githubusercontent.com/1362745/48876339-79922400-ee38-11e8-9e60-f4467f2d9eb0.png">

**Comment by jeevatkm** [comment]
@wanyixue Could you enable `Debug` mode, steps are below? 

RWH add-on debug log:

* First enable the debug log via add-on preferences on About Tab - Check Enable debug mode
* Then open Error Console window by pressing  on macOS `Shift + Command + J` and on Windows `Shift + Ctrl + J`
* Now do both Reply and Reply All behavior on the emails you have an issue
* Share all the debug line starts with RWH from the error console window to my email address `jeeva @ myjeeva.com`

**Comment by jeevatkm** [comment]
@wanyixue Today I was verifying RWH with TB 60.3.3 on my Mac book 10.14.1 with my gmail account add-on seems to work alright. I don't have Mac OS environment at my end. Not sure how to proceed on it.

**Comment by jeevatkm** [comment]
@wanyixue I have prepared the `v2.1.0.beta.1`, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by jeevatkm** [comment]
I'm closing this one!
