### ISSUE TITLE
May I have a not-html style and translate in italian?

### ISSUE THREAD

**Issue by gabri25ele** [jeevatkm/ReplyWithHeaderMozilla#74]
May I have a style like this in my reply: (not html)

-----Messaggio originale-----
Da: somebody@email_provider.com
A: you@email_provider.com
Inviato: mercoledì 28 novembre 2018 11:12
Oggetto: something subject

and where for the italian translate:

From: > Da:
To: > A:
Cc: > Cc:
Subject: > Oggetto:
Date: > Data:
Sent: > Inviato:

Forwarded Message > Messaggio inoltrato
Original Message > Messaggio originale

**Comment by jeevatkm** [comment]
@gabri25ele email format is not controlled by RWH addon. It just follows the TB provided values.  

Could you create a pull request with Italian translation added to this file https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/master/chrome/content/rwh-i18n.js ?

**Comment by jeevatkm** [comment]
@gabri25ele I have prepared the `v2.1.0.beta.1` with Italian locale and much more, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by jeevatkm** [comment]
Its done 😄
