### ISSUE TITLE
Additional line break before signature

### ISSUE THREAD

**Issue by LibertyForce-Gmod** [jeevatkm/ReplyWithHeaderMozilla#75]
When this addon is active, replying to a message adds an additional line break (with br tag) in front of the signature in both HTML and text-only mails.

Using Thunderbird 60.3.1
This does not happen on new mails or forwarding.
The signature is in HTML format, as an external file, but this also happens with internal signatures
Answer is set to "above quote"
Signature is set to "below answer, but above quote"

Having to remove that line break on every reply is a bit annoying, especially since it is inconsistent to both new mails and forwarding, so it would be great if you could look into this.

**Comment by jeevatkm** [comment]
@LibertyForce-Gmod Did you get a chance to check the RWH preferences for header lines setting?

**Comment by LibertyForce-Gmod** [comment]
I tried setting all line breaks to 0 but it doesn't affect the problem. The weird thing is, that the unwanted space is inserted between the mail body and the signature. Not between the signature and the quote header.

Also tried disabling all other addons in case there was a conflict, but I can definitively say that the line break only appears when this addon is active.

**Comment by jeevatkm** [comment]
@LibertyForce-Gmod Thanks for the inputs. I will have a look.

Could you please share the screenshot? (shade the info in the image you don't want to share)

**Comment by jeevatkm** [comment]
@LibertyForce-Gmod I have prepared the `v2.1.0.beta.1`, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by LibertyForce-Gmod** [comment]
@jeevatkm Sorry for the late reply, I wasn't able to test until today.
Unfortunately the problems still exists. Tested on 60.5.1
In addition I also used a clean profile with just this addon installed, with all settings default.

Screenshots from testing:
Reply with addon: https://i.imgur.com/v7GayzJ.jpg
Reply without addon: https://i.imgur.com/s8IF5dO.jpg
New message: https://i.imgur.com/kbgvg7h.jpg

**Comment by jeevatkm** [comment]
@LibertyForce-Gmod Thanks, I will have a look and get back.

**Comment by jeevatkm** [comment]
@LibertyForce-Gmod I have prepared the RWH v2.1.0-beta.2, please give it a try and let me know.

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.2.xpi

**Comment by LibertyForce-Gmod** [comment]
@jeevatkm Thank you. The new version fixed the problem, both an new and old profiles.

**Comment by jeevatkm** [comment]
@LibertyForce-Gmod Thanks for the confirmation. I'm closing this issue.
