### ISSUE TITLE
font size always Medium

### ISSUE THREAD

**Issue by rudi223** [jeevatkm/ReplyWithHeaderMozilla#76]
No matter which font size I select in the add-on, e.g. 8 points or 16 points, Thunderbird sets the font size to "Medium" in the E-Mail. 

As I write all my E-Mails in Font Size "Small" the header is bigger than the text. 
This you can only see when you receive a reply to your reply.
Because the font size selected in the add-on is displayed correcctly in the draft before sending. With 8 the header is displayed small with 16 it is big.

I use Thunderbird 60.3.3

**Comment by jeevatkm** [comment]
@rudi223 Thanks for reporting it. I will verify.

**Comment by jeevatkm** [comment]
@rudi223 I have prepared the `v2.1.0.beta.1`, could you try out with `TB 60.*` and share your feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by rudi223** [comment]
Hi,
thanks for your efforts, but I can't manage to install v2.1.0.beta.1.
If I click the link in the browser, Firefox tells me that the file couldn't be installed, because the download is damaged. 
If I copy the link to Thunderbird Add-on-search it doesn't find anything. Also it doesn't find anything if I look for ReplyWithHeader v2.1.0

**Comment by jeevatkm** [comment]
@rudi223 Thanks, beta version is not published on AMO that's why you could not find it. Just to download the add-on file please use any browser other than Firefox.

**Comment by jeevatkm** [comment]
@rudi223 I have done this TB font detect for the header as part of #64 It seems like It takes away the option choose font RWH preferences. My bad I didn't realize it. I will revert it back to previous behavior.

@zyro23 I'm gonna revert the `msgcompose.font_face` font detect changes. I think it would be okay to select the same font from RWH preferences. This end-user would have better control on the settings.

---

Let's get back to Issue. 

> Regarding font size, I didn't see any changes. I tested size 7 and 26. The text is displayed in different sizes, but the setting is medium.

I'm sorry, I'm unable to understand. Do you mean the fix I have applied for font size settings is not working?

Let's do - 

* Could you please share some screenshots for the issue? 
* Also send some test email to my email address `jeeva at myjeeva.com`?
* Also enable debug log and share by following below steps -
  * First enable the debug log via add-on preferences on About Tab - Check Enable debug mode
  * Then open TB Error Console window by pressing 
     - on macOS `Shift + Command + J` 
     - on Windows/Linux `Shift + Ctrl + J`
  * Now do Reply, Reply All or Forward behavior on the emails you have an issue
  * Share all the debug line starts with `RWH` from the error console window and send to my email address `jeeva at myjeeva.com`

---

I'm attaching some test email screenshots of - "Sending from gmail account to personal domain account using TB".

<img width="705" alt="screen shot 2019-02-11 at 8 16 39 am" src="https://user-images.githubusercontent.com/1175977/52576849-ca7d3d00-2dd5-11e9-9177-14a19358de3e.png">
<img width="710" alt="screen shot 2019-02-11 at 8 16 23 am" src="https://user-images.githubusercontent.com/1175977/52576850-cb15d380-2dd5-11e9-9224-ddab8f7cac25.png">

**Comment by jeevatkm** [comment]
The issue has been addressed and closing it for release.

**Comment by rudi223** [comment]
I just sent an e-mail with screen shots

**Comment by rudi223** [comment]
Didn't recognize that I can answer on the closed issue, so her what I wrote:

Hi,
 
here some screenshots to the issue.
The file names describe what you see.
 
If I send an e-Mail from Thunderbird to Thunderbird and back the problem isn't there for any reason. Maybe because I use the same client for all addresses.
But If I answer an e-mail with TB to Outlook, the Outlook user sees the font sizes selected in TB (small for text / medium for header) not the one selected in RWH.
If then the Outlook user replies to TB, it will take the font size the user sees. Font size medium in my case. 
 
What I do now ist, that I set all headers to small manually before sending, so the header has the same size as my reply-text.
 
By the way, this e-mail is sent from an online front end, not with TB.
 
 
 
Best regards
rudi223
 
 
![01 tb-font-size for reply text](https://user-images.githubusercontent.com/46021384/53016563-2edf7280-344e-11e9-8824-65308adb16c2.png)
![02 tb-font-size for header at rwh 8](https://user-images.githubusercontent.com/46021384/53016564-2f780900-344e-11e9-90c4-7d22a0730acf.png)
![03 tb-font-size for header at rwh 30](https://user-images.githubusercontent.com/46021384/53016565-2f780900-344e-11e9-81cc-027ff06878ea.png)
![04 reply to reply tb to tb at rwh 8](https://user-images.githubusercontent.com/46021384/53016567-30109f80-344e-11e9-9014-606eb8e0e22c.jpg)
![05 reply to reply tb to tb at rwh 30](https://user-images.githubusercontent.com/46021384/53016569-30109f80-344e-11e9-9c9a-22e317299832.jpg)
![06 reply to reply outlook to tb at rwh 8](https://user-images.githubusercontent.com/46021384/53016571-30a93600-344e-11e9-9228-1c3d3f87ccc3.jpg)
![07 reply to reply outlook to tb at rwh 20](https://user-images.githubusercontent.com/46021384/53016574-30a93600-344e-11e9-9e19-b0ee44fb7e59.jpg)

**Comment by rudi223** [comment]
Didn't recognize that I can reply to a closed topic, so her what I wrote:


Hi,
 
here some screenshots to the issue.
The file names describe what you see.
 
If I send an e-Mail from Thunderbird to Thunderbird and back the problem isn't there for any reason. Maybe because I use the same client for all addresses.
But If I answer an e-mail with TB to Outlook, the Outlook user sees the font sizes selected in TB (small for text / medium for header) not the one selected in RWH.
If then the Outlook user replies to TB, it will take the font size the user sees. Font size medium in my case. 
 
What I do now ist, that I set all headers to small manually before sending, so the header has the same size as my reply-text.
 
By the way, this e-mail is sent from an online front end, not with TB.
 
 
Best regards
rudi223
 
![01 tb-font-size for reply text](https://user-images.githubusercontent.com/46021384/53016853-e96f7500-344e-11e9-8be4-ac3c5e097b24.png)
![02 tb-font-size for header at rwh 8](https://user-images.githubusercontent.com/46021384/53016854-e96f7500-344e-11e9-92dd-7f3de9fad796.png)
![03 tb-font-size for header at rwh 30](https://user-images.githubusercontent.com/46021384/53016855-e96f7500-344e-11e9-8c8e-a0b30aae1646.png)
![04 reply to reply tb to tb at rwh 8](https://user-images.githubusercontent.com/46021384/53016856-ea080b80-344e-11e9-98cb-7097d73dcbb3.jpg)
![05 reply to reply tb to tb at rwh 30](https://user-images.githubusercontent.com/46021384/53016858-ea080b80-344e-11e9-9ac5-06c681fd1bc2.jpg)
![06 reply to reply outlook to tb at rwh 8](https://user-images.githubusercontent.com/46021384/53016860-ea080b80-344e-11e9-9e6a-69458a96466a.jpg)
![07 reply to reply outlook to tb at rwh 20](https://user-images.githubusercontent.com/46021384/53016861-eaa0a200-344e-11e9-9626-4bf4866cd5cd.jpg)

**Comment by rudi223** [comment]
Didn't recognize that I can reply to a closed topic, so her what I wrote:

Hi,

here some screenshots to the issue.
The file names describe what you see.

If I send an e-Mail from Thunderbird to Thunderbird and back the problem isn't there for any reason. Maybe because I use the same client for all addresses.
But If I answer an e-mail with TB to Outlook, the Outlook user sees the font sizes selected in TB (small for text / medium for header) not the one selected in RWH.
If then the Outlook user replies to TB, it will take the font size the user sees. Font size medium in my case.

What I do now ist, that I set all headers to small manually before sending, so the header has the same size as my reply-text.

By the way, this e-mail is sent from an online front end, not with TB.

Best regards
rudi223

![01 tb-font-size for reply text](https://user-images.githubusercontent.com/46021384/53017001-479c5800-344f-11e9-83c4-1415926b905b.png)
![02 tb-font-size for header at rwh 8](https://user-images.githubusercontent.com/46021384/53017002-4834ee80-344f-11e9-98b2-b78c3e2812f0.png)
![03 tb-font-size for header at rwh 30](https://user-images.githubusercontent.com/46021384/53017003-4834ee80-344f-11e9-8785-bd8ed9eff953.png)
![04 reply to reply tb to tb at rwh 8](https://user-images.githubusercontent.com/46021384/53017004-4834ee80-344f-11e9-9d8b-5ccd827b1d03.jpg)
![05 reply to reply tb to tb at rwh 30](https://user-images.githubusercontent.com/46021384/53017005-48cd8500-344f-11e9-9a0c-dabddae4d2e4.jpg)
![06 reply to reply outlook to tb at rwh 8](https://user-images.githubusercontent.com/46021384/53017006-48cd8500-344f-11e9-9882-e8c7150b6001.jpg)
![07 reply to reply outlook to tb at rwh 20](https://user-images.githubusercontent.com/46021384/53017007-48cd8500-344f-11e9-84aa-8a33d7e4a4f5.jpg)

**Comment by jeevatkm** [comment]
@rudi223 Thank you for the detailed response. I have surely done few font, font size fixes in `v2.1.0` you could see HTML that via debug mode (enabling on About Tab on preferences) and TB error console (Shift + Cmd/Ctrl + J).

I will re-open this issue. Honestly, I don't have a clue on "how to fix the inconsistent between outlook client TB", needs some investigation.

Also, one thing it could be very helpful from your end is to provide (via email as an attachment) complete message source of TB -> Outlook and Outlook -> TB. I will use to investigate further.

**Comment by rudi223** [comment]
Again, thanks for all your efforts.

I don't have Outlook. I asked a friend to send an e-mail and to reply to my reply. 
Do you have Outlook or a friend with knowledge in IT using it? 
Source code, etc. is to "deep" for me.

By the way I'll open a new point.

**Comment by jeevatkm** [comment]
@rudi223  I will try to create email chain with outlook.

**Comment by jeevatkm** [comment]
Closing it, many improvements happened in the RWH; please open a new one for the issue. Thanks
