### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by markstetz** [jeevatkm/ReplyWithHeaderMozilla#77]
Thunderbird 60.5.0 (64 bit)
Mac OSX 10.14.2

Installed RWH and restarted Tbird. Absolutely no reply header in replied messages - even less than the default Tbird one. Changed settings, restarted Tbird several times - nothing. Left in disabled mode so that there would be at least one reply line instead of none. I am not a programmer and have no interesting in debugging code. Any idea why the reply is non-existent? What manner of user error is this?

**Comment by jeevatkm** [comment]
@markstetz Thanks for reporting it. I understand what you mean regarding user error. Basically it's difficult to detect errors in TB until fails, so always user help is needed to debug any issues it pop up in  TB.

As you might aware; TB is going through lot of internal design changes, so its very possible get broken easily unlike TB 52.* before. There are known add-on incompatibilities issues also upcoming in TB 64.* and add-on (not sure many add-ons are ready for it, surely RWH is not yet ready for that).

I believe, it's easy to help me. Before I share the steps. I would like to convey, I'm using exactly same version (TB 60.5.0, RWH v2.0 and macOS 10.14.2) with gmail account configured in it. Add-on is doing alright. 

I need your help to figure out the issue you're getting. Please follow below steps and let me know.

**RWH add-on debug log:**

* First enable the debug log via add-on preferences on About Tab - Check Enable debug mode
* Then open TB Error Console window by pressing 
   - on macOS `Shift + Command + J` 
   - on Windows/Linux `Shift + Ctrl + J`
* Now do Reply, Reply All or Forward behavior on the emails you have an issue
* Share all the debug line starts with `RWH` from the error console window and send to my email address `jeeva @ myjeeva.com`

**Comment by markstetz** [comment]
Jeevanandam-
    The debug console readout is below. I also noticed that Tbird
      ignores the 'reply to' field, which will require another add-in to
      fix. Your e-mail address also had spaces in it, which may be
      intentional. Note the lack of a reply below. 
    
    Thanks for looking in to this. 
    
    
    
    
      
      RWH   DEBUG    Initializing RWH
      RWH   DEBUG    Current mail type: HTML
      RWH   DEBUG    Reply or ReplyAll mode
      RWH   DEBUG    Signature settings: inserts above the quote
      RWH   DEBUG    Message URI:
      imap-message://mark.l.stetz%40gmail.com@imap.googlemail.com/INBOX#22656
      RWH   DEBUG    Locale date format
      TypeError: tzAbbr[1].match(...) is null[Learn More]  rwh.js:215:16
          tzAbbr chrome://replywithheader/content/rwh.js:215:16
          parseDate chrome://replywithheader/content/rwh.js:236:12
          parseMsgHeader chrome://replywithheader/content/rwh.js:421:15
          get createRwhHeader
      chrome://replywithheader/content/rwh.js:468:19
          handleReplyMessage
      chrome://replywithheader/content/rwh.js:715:5
          handleMailCompose
      chrome://replywithheader/content/rwh.js:1004:9
          NotifyComposeBodyReady
      chrome://replywithheader/content/rwh.js:982:7
      
        -- 
          
          
          
          
          
          
    p.p1 {margin: 0.0px 0.0px 6.0px 0.0px; line-height: 14.0px; font: 12.0px Times; color: #000000; -webkit-text-stroke: #000000}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 15.0px; font: 12.0px 'Times New Roman'; color: #000000; -webkit-text-stroke: #000000}
    p.p3 {margin: 0.0px 0.0px 12.0px 0.0px; line-height: 14.0px; font: 12.0px Times; color: #000000; -webkit-text-stroke: #000000}
    span.s1 {font-kerning: none}
  
          ________________________________________________________________________
          Mark Stetz
          AZ & CO USA
              
          Mobile/WhatsApp:
              +1-970-946-9150 
          E-mail: Mark.L.Stetz@gmail.com 
          Skype: mark.stetz
          
            
        
      
    
    
    
      
      @markstetz
        Thanks for reporting it. I understand what you mean regarding
        user error. Basically it's difficult to detect errors in TB
        until fails, so always user help is needed to debug any issues
        it pop up in TB.
      As you might aware; TB is going through lot of internal design
        changes, so its very possible get broken easily unlike TB 52.*
        before. There are known add-on incompatibilities issues also
        upcoming in TB 64.* and add-on (not sure many add-ons are ready
        for it, surely RWH is not yet ready for that).
      I believe, it's easy to help me. Before I share the steps. I
        would like to convey, I'm using exactly same version (TB 60.5.0,
        RWH v2.0 and macOS 10.14.2) with gmail account configured in it.
        Add-on is doing alright.
      I need your help to figure out the issue you're getting. Please
        follow below steps and let me know.
      RWH add-on debug log:
      
        First enable the debug log via add-on preferences on About
          Tab - Check Enable debug mode
        Then open TB Error Console window by pressing
          
            on macOS Shift + Command + J
            on Windows/Linux Shift + Ctrl + J
          
        
        Now do Reply, Reply All or Forward behavior on the emails
          you have an issue
        Share all the debug line starts with RWH from
          the error console window and send to my email address jeeva
            @ myjeeva.com
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jeevatkm/ReplyWithHeaderMozilla","title":"jeevatkm/ReplyWithHeaderMozilla","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jeevatkm/ReplyWithHeaderMozilla"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jeevatkm in #77: @markstetz Thanks for reporting it. I understand what you mean regarding user error. Basically it's difficult to detect errors in TB until fails, so always user help is needed to debug any issues it pop up in  TB.\r\n\r\nAs you might aware; TB is going through lot of internal design changes, so its very possible get broken easily unlike TB 52.* before. There are known add-on incompatibilities issues also upcoming in TB 64.* and add-on (not sure many add-ons are ready for it, surely RWH is not yet ready for that).\r\n\r\nI believe, it's easy to help me. Before I share the steps. I would like to convey, I'm using exactly same version (TB 60.5.0, RWH v2.0 and macOS 10.14.2) with gmail account configured in it. Add-on is doing alright. \r\n\r\nI need your help to figure out the issue you're getting. Please follow below steps and let me know.\r\n\r\n**RWH add-on debug log:**\r\n\r\n* First enable the debug log via add-on preferences on About Tab - Check Enable debug mode\r\n* Then open TB Error Console window by pressing \r\n   - on macOS `Shift + Command + J` \r\n   - on Windows/Linux `Shift + Ctrl + J`\r\n* Now do Reply, Reply All or Forward behavior on the emails you have an issue\r\n* Share all the debug line starts with `RWH` from the error console window and send to my email address `jeeva @ myjeeva.com`"}],"action":{"name":"View Issue","url":"https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/77#issuecomment-460514056"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/77#issuecomment-460514056",
"url": "https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/77#issuecomment-460514056",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jeevatkm** [comment]
@markstetz Thank you for providing the debug log. Log info has failure details, I will fix this and once beta version is ready I will request for try out.

Yes, space in the email address is intentional. 

Regarding `Reply-To` header, typically its not included in the header composition. I would like to understand what you're trying to convey?

**Comment by jeevatkm** [comment]
@markstetz I have prepared the `v2.1.0.beta.1`, could you try out with `TB 60.*` and share feedback?

https://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v2.1.0-beta.1.xpi

**Comment by jeevatkm** [comment]
Its done 😄
