### ISSUE TITLE
"From:"-line empty

### ISSUE THREAD

**Issue by rudi223** [jeevatkm/ReplyWithHeaderMozilla#81]
Hi, 

when I reply to e-mails in some of my messages the "From:"-line in the header stays empty.
"From:" is there, but no e-mail address or name beside it.
The other lines (Sent, To, Subject) seem to work normal.

That "From:" is empty only seems to happen with e-mails which do not include the name of the sender. Messages which only have the e-mail address of the sender in the from-field.
e.g. "john@doe.com" instead of "John Doe" or "John Doe < john@doe.com >" .

My standard settings:
![anmerkung 2019-02-22 141353](https://user-images.githubusercontent.com/46021384/53245096-0f925080-36ad-11e9-978e-b35c44badd67.jpg)

When I use the setting Outlook Extended, the e-mail address is shown.  [mailto:.......]

Using TB 60.5.1

**Comment by jeevatkm** [comment]
@rudi223 Can you try the option of `Default` and let me know? 

_FYI, RWH does NOT lookup any contacts to From header or any. RWH just uses the email header and its values provided by TB._

**Comment by rudi223** [comment]
It works with settings in Default

**Comment by jeevatkm** [comment]
@rudi223  Good to know it works on Default settings. Could you please enable debug log and perform reply without default settings and share the logs here?

RWH add-on debug log:

* First enable the debug log via add-on preferences on About Tab - Check Enable debug mode
* Then open TB Error Console window by pressing 
   - on macOS `Shift + Command + J` 
   - on Windows/Linux `Shift + Ctrl + J`
* Now do Reply, Reply All or Forward behavior on the emails you have an issue
* Share all the debug line starts with `RWH` from the error console window

**Comment by jeevatkm** [comment]
Closing it, many improvements happened in the RWH; please open a new one for the issue. Thanks
