### ISSUE TITLE
"reply to list" isn't supported

### ISSUE THREAD

**Issue by johnsonb88** [jeevatkm/ReplyWithHeaderMozilla#82]
On messages for which the "Reply to mailing list" button is active (due to the presence of a "List-Post:" header? not sure) replying to the list does not trigger ReplyWithHeader.  The default Thunderbird reply formatting is used.

**Comment by jeevatkm** [comment]
@johnsonb88 I'm sorry, RWH doesn't support Mailing List. It works only for Reply/Reply All/Forward for emails.

**Comment by jeevatkm** [comment]
I think implementing #83 will provide a way for Mailing list users to disable RWH on-demand easily and enable it back.
