### ISSUE TITLE
RFE:  toolbar button or menu item do temporarily disable ReplyWithHeader

### ISSUE THREAD

**Issue by johnsonb88** [jeevatkm/ReplyWithHeaderMozilla#83]
Sometimes, for example if I'm replying to a message from a mailing list which disallows top-posting, I prefer to use the default Thunderbird reply formatting.  The RWH Preferences tab has a top-level "Enable" checkbox which makes it fairly easy to disable and enable ReplyWithHeader.  But accessing it requires wading through the Add-ons screen, or leaving the tab open all the time.

It would be handy to have a toolbar button or menu check item to enable and disable ReplyWithHeader.  Or to have a way to disable ReplyWithHeader for a single reply.

Thanks!

**Comment by jeevatkm** [comment]
@johnsonb88 Good idea, I will bring this option 😄

**Comment by jeevatkm** [comment]
@johnsonb88 At last, the feature is implemented in RWH v3.0.0.beta2! Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2114025131
