### ISSUE TITLE
Feature request: Prepend '>' to header

### ISSUE THREAD

**Issue by janblaesi** [jeevatkm/ReplyWithHeaderMozilla#84]
Hi! 
I really appreciate your addon! But there is one thing that would make it even better :D

I like to have the quote character enabled and would love to have the option to move the Reply header into the quote (like RWH for Apple Mail is doing it), would that be possible?
<img width="804" alt="Screenshot 2019-05-24 at 15 11 21" src="https://user-images.githubusercontent.com/44644172/58330091-6cc9a980-7e36-11e9-8a31-26bb8a207c91.png">

Greetings,
Jan

**Comment by jeevatkm** [comment]
@janblaesi Thank you for your inputs. I will have a look, I could have tried that and might have left behind that idea.  Since TB and Apple Mail works very different internally 😄 I'm sorry, I don't remember it clearly.

I will give it try!

**Comment by jeevatkm** [comment]
I'm closing it. Thanks.
