### ISSUE TITLE
Forwarding a draft email without a sender eats line 1 of body

### ISSUE THREAD

**Issue by cakepuller** [jeevatkm/ReplyWithHeaderMozilla#85]
RWH version 2.1.0, TB 60.7.2 (32bit)
Steps to reproduce:

- Compose an email > Don't specify any recipient > Type some lines > Save as Draft
- Goto Draft folder > highlight the Draft email > Forward
- Result is a forwarded email with the first line of the email missing.

Not a big issue, but this use case is what I use quite often, so, a teeny bit annoying. :)  I can get around it by specifying a recipient, but then that's one extra unnecessary step. :D
This issue goes away when I disable RWH.

THANKS for creating this addon! :)

**Comment by jeevatkm** [comment]
@cakepuller Thank you for reporting an issue and your appreciation.

Currently, the above-mentioned scenario I have not tested. I will have to try it out at my end to see what goes wrong in it.

**Comment by jeevatkm** [comment]
@cakepuller Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
