### ISSUE TITLE
incompatible with TB69 (beta)

### ISSUE THREAD

**Issue by n8v8R** [jeevatkm/ReplyWithHeaderMozilla#86]
Operating System: W10 Pro x_64 v1903 b18362.267
Thunderbird: 69.0b1 (64-bit)
RWH: 2.1.0
_____
![Annotation 2019-07-29 165313](https://user-images.githubusercontent.com/13611490/62062295-0a6f9980-b229-11e9-966e-2c1330d5dcc9.png)

**Comment by jeevatkm** [comment]
I think it might work once I finish #88, so closing this one. Thanks.
