### ISSUE TITLE
Add support for TB 68.0

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeaderMozilla#88]
The goal of this issue to identify the necessary updates required for RWH to make it work in TB 68.0

**Please Note:** I have to learn and perform this upgrade, it might take a while due to my day work commitments. However, I will surely add support :smile:

**Comment by jeevatkm** [comment]
Collected notes:
* https://support.mozilla.org/en-US/kb/new-thunderbird-68
* https://www.thunderbird.net/en-US/thunderbird/68.0beta/releasenotes/

**Comment by wikiaal** [comment]
Please, give support. I had to go back to TB 60.9.0 because your add-on doesn't work with TB 68.0.

**Comment by WesleyGeneroso95** [comment]
+1
Please, give support to the TB 68.0.

**Comment by FxRe** [comment]
People, he already announced that he's working on it. I don't think it'll go any faster, if you just reply "Please, give support"... If you want it so badly, you'll have to be more productive.

**Comment by wikiaal** [comment]
> People, he already announced that he's working on it. I don't think it'll go any faster, if you just reply "Please, give support"... If you want it so badly, you'll have to be more productive.

Thunderbird 68 had been published in beta for 2 months ... maybe think about it a little earlier ...

**Comment by FxRe** [comment]
> Thunderbird 68 had been published in beta for 2 months ... maybe think about it a little earlier ...
Even if it had been published 2 decades ago, that doesn't make a difference at all right now.

**Comment by jeevatkm** [comment]
@FxRe Thank you for your understanding and support.

@wikiaal Thanks for sharing your concerns. From RWH user standpoint, it's very valid. 

I want to share my situation and perspective. I love doing open-source projects and do my best with my limited time along with day work, family, personal, etc.  So, I wait until the final version comes out. Then I search for documentation for changes needs to performed, sometimes due to unavailable documentation; I have to take an additional step to learn from fellow add-on developers by reverse engineering. 

_Spicy on Top: The past couple of years TB has been releasing quite no. of breaking changes and its good for TB roadmap but it brings challenges to add-on developers. Also, TB has very very limited documentation in these scenarios._ 

I kindly request you to recognize that fact and provide support.

**Comment by wikiaal** [comment]
Of you need someone to make tests with upcoming RWH for TB v68 please ask.

**Comment by insekt** [comment]
Please add support for Thunderbird 68. I'm in 1 step from switching to Outlook =(

**Comment by dpate71** [comment]
Any news on RWH compatibility for TB 68?

**Comment by athanas55** [comment]
> Please add support for Thunderbird 68. I'm in 1 step from switching to Outlook =(

Maybe you should, if you think 5 dollars for the other plugin that does the same job (and a bit more) doesn't worth it.

**Comment by n8v8R** [comment]
@athanas55 Which plugin is that?

**Comment by insekt** [comment]
> Maybe you should, if you think 5 dollars for the other plugin that does the same job (and a bit more) doesn't worth it.

Could you point me to that plugin?

**Comment by jeevatkm** [comment]
Hello All - 

I have created a working version `RWH v2.2.0-beta` addon for TB 68 plus version. However, **_there is an issue yet be sorted out is RWH preferences (no errors, needs investigation)_**.

Download link: http://bit.ly/2MFswW5

In the meantime, can you please try and share your feedback.

Cheers, Jeeva

**Comment by wikiaal** [comment]
Dear Jeeva, thank you very much for your work!!! I've just upgraded (in my secondary laptop) to TB 68.1.2 and installed RWH 2.2 beta. I'll send you a feedback a.s.a.p.

**Comment by jeevatkm** [comment]
@wikiaal Thank you for your help, appreciated 👍

**Comment by wikiaal** [comment]
Dear Jeeva,
first test with TB 68.1.2: the RWH 2.2.beta seems to work properly for mail reply and forward, but I have no access to RWH settings (I see only deactivate and remove buttons, no settings button anywhere).

**Comment by insekt** [comment]
@jeevatkm thank you very much!
@wikiaal confirm the same behaviour.

**Comment by zdenekvecera** [comment]
@jeevatkm, thank you very much!

**Comment by n8v8R** [comment]
WFM with 70.0b3 (64-bit) on WIN 10 Pro v1903 x_64, except no settings to access.
____
Just thought to mention about the display of settings:

This MX (mail extension) https://mailredirect.sourceforge.io for example integrates its settings with the main Options -> Composition UI

![Annotation 2019-10-15 123509](https://user-images.githubusercontent.com/13611490/66824289-4a047280-ef48-11e9-8a78-4c5f4c67de88.png)

Whilst this one https://github.com/lieser/dkim_verifier features its own tab

![Annotation 2019-10-15 123509](https://user-images.githubusercontent.com/13611490/66824621-ed558780-ef48-11e9-9332-2c20069fc653.png)

**Comment by WesleyGeneroso95** [comment]
Dear Jeeva, 
I'm testing the plugin with TB 68.1.2 and everythings seems to work great.

**Comment by athanas55** [comment]
> > Maybe you should, if you think 5 dollars for the other plugin that does the same job (and a bit more) doesn't worth it.
> 
> @athanas55 Could you point me to that plugin?

@insekt Try searching for SmartTemplate4

**Comment by wikiaal** [comment]
> > > Maybe you should, if you think 5 dollars for the other plugin that does the same job (and a bit more) doesn't worth it.
> > 
> > 
> > @athanas55 Could you point me to that plugin?
> 
> @insekt Try searching for SmartTemplate4

SmartTemplate4 is more complex (and less reliable) to use than RWH and isn't free.

**Comment by m-i-k-e-y** [comment]
@jeevatkm: The beta you provided is working for me. Thank you!

This is the only thing I've found in the error console related to this extension:

> 1571159586588	addons.webextension.replywithheader@myjeeva.com	WARN	Loading extension 'replywithheader@myjeeva.com': Reading manifest: Error processing xpi-name: An unexpected property was found in the WebExtension manifest.

**Comment by alphp** [comment]
@jeevatkm thank you very much!
@wikiaal confirm the same behaviour.

**Comment by jeevatkm** [comment]
Thank you @wikiaal, @zdenekvecera, @insekt, @WesleyGeneroso95, @m-i-k-e-y, @alphp for trying out and sharing your feedback.

Once I sort out the implementation of the RWH settings, I will make a few more beta releases to ensure everything works then I will do a final release.

----

I want to provide internal details of TB and its roadmap. How it's affecting the addons. 

Since TB 68 addon model is changed to WebExtension/MailExtension. all the changes I'm doing will be good until version TB 78. So a permanent solution is to rewrite the RWH addon into the WebExtension model. I will learn and do it later on.

**Comment by jeevatkm** [comment]
Hello All -

I have prepared the next beta version with RWH preferences issues fixed. Can you please test it out and provide your feedback?

Download link: http://bit.ly/2BtWMOx

I will wait for couple of weeks, If everything working alright then I will bump the release version to `v3.0.0` and I will submit it to AMO.

Cheers, Jeeva

**Comment by wikiaal** [comment]
Hi Jeeva,
first of all thank you very much for the work done!!!

Just installed and tested the new RWH v2.2.1-beta:

- Good and identical results in Reply and Forward (both functions seem to work well).
- I would just like to make a remark: the Reply/Forward headings use a (forced) font (Thaoma) other than the default one that is set in Thunderbird as (Latin) Sans Serifs (Calibri); in other words, the header font does not fit with the format of the body.
- Still cannot find "Settings" button anywhere.

With my best regards
Andrea

**Comment by jeevatkm** [comment]
Hello Andrea - 
Thank you for your feedback. 

* I will work on default font once I address the TB 68+ support also there is an enhancement/bug request needs to be done too
* TB moved that to 
       - For windows/linux  "Tools -> Addon Options -> RWH Preferences"
       - For mac "Tools -> Addon Preferences -> RWH Preferences"  - (Please note: It seems TB has some bug, sometimes it does not show up the options for me)

Cheers, Jeeva

**Comment by zdenekvecera** [comment]
@jeevatkm, thank

**Comment by zdenekvecera** [comment]
@jeevatkm, thank you very much.

I couldn't change my settings in a previous beta. But in this new RWH v2.2.1-beta the settings works again. Great!

**Comment by m-i-k-e-y** [comment]
@jeevatkm Thanks again. Settings do open for me and seem to work so far.

The error message I've seen with the previous beta is gone too in the error console, only this warning is left:

> Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:16

That points to this line in the manifest of your addon:

> overlay chrome://messenger/content/messengercompose/messengercompose.xul    chrome://replywithheader/content/messengerComposeOverlay.xul

Keep up the good work!

**Comment by wikiaal** [comment]
@jeevatkm & @zdenekvecera: why I cannot find "settings" anywhere in the new RWH v2.2.1-beta?

**Comment by house67** [comment]
Jeeva,
as far as i can see RWH v2.2.1-beta works really fine.

many tks

**Comment by feddnoai** [comment]
Hi Jeeva,

reply and forward work properly. Preferences are not being displayed under Tools>Add-on Preferences. Tried it a couple of times. I won´t give up! ;)

**Comment by wikiaal** [comment]
Hi Jeeva,
after some more tests, I've found an issue with RWH:  replying to some mails, with Forward function I have the same format of the header (body text, font), with Reply function the body text format becomes different (preformatted?) with plain fixed lenght font while the header remain body text as in Forward function.

**Comment by athanas55** [comment]
Hello Jeeva
Just installed the beta and its performing as it should until now. 
System: W10, 64bit, v.1903, 
TB: 68.2.0, 64bit.
In case any bugs come up I'll report them here.
Thank you for your efforts and dedication to open-source projects.

Thanos

**Comment by jc97** [comment]
Hello,

I tried the beta version too and it is working perfectly for me. I think you can bump the release. 

Thanks!

**Comment by netjeff** [comment]
Just found this thread.  Installed the beta, and works perfectly.  Looking forward to the official release. Thanks @jeevatkm!  I just [donated](https://myjeeva.com/replywithheader-mozilla#donators), hopefully lots of people will donate for your great work.

**Comment by jeevatkm** [comment]
Dear All - FYI, RWH v2.2.1 release version submitted to AMO for approval.

**Comment by wikiaal** [comment]
Hi Jeeva,
thank you so much for your invaluable work, look forward for final 2.2.1 version of RWH.

With my best regards
Andrea

**Comment by jeevatkm** [comment]
Hello @wikiaal - I'm wondering. is these are your reviews? if yes, do you mind updating the review and stars?

https://addons.thunderbird.net/en-US/thunderbird/addon/replywithheader/reviews/user:13652970

Regards,
Jeeva
