### ISSUE TITLE
New Header label attribution request

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeaderMozilla#89]
At last (very delayed), I'm creating an issue here since user does not have GitHub user account. RWH user reached out via email.

----
**Email Details:**

From: Mehdi Alimadadi
Sent: November 9, 2018 at 8:46:29 AM PST
To: jeeva@myjeeva.com
Subject: ReplyWithHeader

Hi Jeevanandam,

Thank you for ReplyWithHeader version 2.0. I would like to say that when I reply to an email that was sent to me, I have this as the reply header:

From: Facebook [mailto:notification@facebookmail.com]
Sent: Fri, Nov 9, 2018 12:00 AM GMT
To: Mehdi Alimadadi
Subject: New Mail

Since I have several email addresses, to distinguish between different accounts, can you please make the "To:" line like this:

To: &lt;full-name-here> [mailto:&lt;email-address-here>]

Also, because I have troubles with Thunderbird's internal font management, I was wondering if you could make a new add-on to set the default font size, format, etc. for outgoing emails and for incoming text emails. Something like a default template that always would be used. Previously, I was using "Quote and compose manager" from (https://freeshell.de/~kaosmos/quoteandcomposemanager-en.html) which last updated a few years ago and is not compatible with Thunderbird 60+. 

Take care,
Mehdi

**Comment by llvs** [comment]
Hi Jeevanandam,
I don't know, if mailto: with angle brackets is allowed (like suggested in previous post), but I would also welcome the addition to have Outlook Extended style using angle brackets like:
Name <name@mail.com>
instead of the current
Name [mailto:name@mail.com]
Best regards
weaker

**Comment by jeevatkm** [comment]
Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608
