### ISSUE TITLE
Feature request: make the addon choosable per reply

### ISSUE THREAD

**Issue by wehkah** [jeevatkm/ReplyWithHeaderMozilla#91]
Hello and thanks for this wonderful addon!

Sometimes you need to use Outlook style, sometimes you don't. This addon would be even more handy if it could be enabled or disabled on each written reply, for example by clicking a button in the compositor's menu bar.

**Comment by jeevatkm** [comment]
@wehkah Now, RWH v3.0.0.beta2 is ready! Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2114025131
