### ISSUE TITLE
ISO date format

### ISSUE THREAD

**Issue by ygoe** [jeevatkm/ReplyWithHeaderMozilla#93]
An internationally understood time format would be better for global recipients. Instead of deciding on one language/culture and localised formatting and timezone shortnames, could there be a time format like "2019-06-09, 16:14 (+0200)"? I'd suggest adding a checkbox to enable this format in favour of a localised one.

**Comment by jeevatkm** [comment]
I'm sorry, but I'm unable to implement this option. Thanks.

**Comment by ygoe** [comment]
No worries, I've done it myself and just use my fixed version since then. I contains more fixes that you rejected.

**Comment by jeevatkm** [comment]
> contains more fixes that you rejected.

@ygoe If it’s okay, could you share the fixes you're referring to? If it is a generalized version of implementation, I will aim to  incorporate it in the upcoming release.

**Comment by ygoe** [comment]
https://github.com/ygoe/ReplyWithHeaderMozilla/tree/iso8601-date-format
