### ISSUE TITLE
Use default font

### ISSUE THREAD

**Issue by ygoe** [jeevatkm/ReplyWithHeaderMozilla#94]
Why do I have to set a font, size and colour for the inserted headers? Can't the header just use the default sans-serif font and text style? I'd suggest adding a checkbox above that section to use a custom style. If unchecked, no custom style will be applied (except the bold style for header titles).

**Comment by jeevatkm** [comment]
Use the System font and color option added in the v2.6.0 release.

**Comment by ygoe** [comment]
@jeevatkm Okay, tell me how? I don't see it.

**Comment by jeevatkm** [comment]
Via RWH options
<img width="925" alt="Screenshot 2023-10-11 at 7 39 35 PM" src="https://github.com/jeevatkm/ReplyWithHeaderMozilla/assets/1175977/35c214b3-2a3c-4433-aec2-fe8357b75074">

**Comment by jeevatkm** [comment]
@ygoe ^

**Comment by ygoe** [comment]
Mhm. Those are not there in my copy of the add-on. Do we have different v2.6.0?

**Comment by jeevatkm** [comment]
@ygoe, there is only one version of the TB 115 version support. You could try uninstall and restart, then reinstall.

**Comment by ygoe** [comment]
Apparently I had a different version 2.6.0 than is currently available for installation. After uninstalling it and reinstalling from the addons page the two checkboxes are there. But they have no visible effect. Whatever font, size and colour I set will be used. Why can I even still select these values when the default option is selected?

So the issue remains unresolved.
