### ISSUE TITLE
Feature request: remove <blockquote> in replies

### ISSUE THREAD

**Issue by cakepuller** [jeevatkm/ReplyWithHeaderMozilla#95]
Hi Jeevanandam
**Many thanks** for your addon.  It's very useful to me and am grateful for your efforts.  I'm using RWH 2.1.0 on Thunderbird 60.9.0.

May I please request for a feature to omit the **\<blockquote\>** tag in the replies (in html).  The **\<blockquote\>** tag causes undesired indentation of the replied text as shown in the attached screenshot.    The problem with the **\<blockquote\>** is: when there are multiple quoted replies in one email, say 20 replies, the quoted emails become more and more indented to the right causing the bottom-most email to be so far indented to the right that reading it becomes difficult as one line can then contain only one word.

The desired result when replying is to have all replies _Left-justified_ without indentation. 

Hope you can consider this request.
Thanks again for your work on this thus far.

![multiple-indents-annoyance](https://user-images.githubusercontent.com/40509717/69017890-9aa63a00-09e4-11ea-8826-62d9f25d0578.png)

**Comment by jeevatkm** [comment]
@cakepuller I think this option "Cleanup the blockqoute colors" might be already working in RWH, can you verify it. Basically this option will remove color and left padding.

Please let me know.

**Comment by cakepuller** [comment]
> 
> 
> @cakepuller I think this option "Cleanup the blockqoute colors" might be already working in RWH, can you verify it. Basically this option will remove color and left padding.
> 
> Please let me know.

I'm afraid it doesn't clear the blockquote tags.  I had tried turning on options "Cleanup the blockquote colors" and "Cleanup only new blockquote color", in various combinations, but the blockquote tag is still there when clicking Reply.  

Is this perhaps because even without RWH installed, native TB still inserts the blockquote tag upon Reply?

**Comment by jeevatkm** [comment]
@cakepuller I'm sorry for the delayed response. Typically RWH never removes the blockquote, since it will disturb the email formatting done by TB. RWH just updates the style values to make it invisible on UI and technically email source will still have blockquote in it.

**Comment by cakepuller** [comment]
@jeevatkm No problem, thanks for your hardwork in putting RWH out.
