### ISSUE TITLE
No Signature on Forward TB 68.7

### ISSUE THREAD

**Issue by Koala66** [jeevatkm/ReplyWithHeaderMozilla#97]
Hello,

thank you very much for your tool. The only easy way to remove the blockquotes easily with Thunderbird 68.7. Unfortunately if I switch it on, there are no signatures on mail forward anymore. It works for mail reply and new mail - but not forward. - If I switch the add-on off, it works for forward.

With my best regards

Koala66

**Comment by jeevatkm** [comment]
@Koala66 Thanks for reporting an issue and your appreciation.

I need further info, can you provide info? please follow the below steps.

RWH add-on debug log:

* First enable the debug log via add-on preferences on About Tab - Check Enable debug mode
* Then open TB Error Console window by pressing 
   - on macOS `Shift + Command + J` 
   - on Windows/Linux `Shift + Ctrl + J`
* Now do Reply, Reply All or Forward behavior on the emails you have an issue
* Share all the debug line starts with `RWH` from the error console window and send to my email address `jeeva @ myjeeva.com`

**Comment by 2BeeOrNot** [comment]
Check here and see if replies and forwards are checked. If not checked RWH generates the following entries in the error console:

RWH  DEBUG   Signature not exists

![image](https://user-images.githubusercontent.com/63317977/79054088-1ad97000-7c10-11ea-821e-54eccc2a1b2d.png)

**Comment by Koala66** [comment]
There is everything checked. But no signature if I forward.


With my best regards

Robert Kahl

------------------------------------------------------------------------

------------------------------------------------------------------------
*From:* 2BeeOrNot
*Sent:* Saturday, April 11, 2020, 22:23 UTC+2
*To:* jeevatkm/ReplyWithHeaderMozilla 
<ReplyWithHeaderMozilla@noreply.github.com>
*Cc:* Koala66 <rkahl@live.de>, Mention <mention@noreply.github.com>
*Subject:* [jeevatkm/ReplyWithHeaderMozilla] No Signature on Forward TB 
68.7 (#97)

**Comment by 2BeeOrNot** [comment]
Signature works for me for new, reply and forward on TB 68.7 and macOS 10.15.4.
Did you enable debug mode and look for 'RWH DEBUG Signature not exists' in error console?
Are you using Windows? I can check on an old Windows 7 PC later. Any other addons that could cause the problem?

**Comment by Koala66** [comment]
Hello,

I thought I sent you this log:


window.controllers/Controllers sollte nicht mehr verwendet werden. 
Verwenden Sie es nicht für die Browser-Erkennung. blank <about:blank>
RWH DEBUG Initializing ReplyWithHeader v2.2.1 (Thunderbird 68.7.0, 
Windows, 20200407160932)
RWH DEBUG Email content-type: HTML
RWH DEBUG Email compose type: Forward
RWH DEBUG Message URI: imap-message://R.Kahl@192.168.36.254/INBOX#15937
RWH DEBUG Date format: Locale (en-US), Time format: 24-hour, Include 
short timezone info
RWH DEBUG From: JACK WOLFSKIN
RWH DEBUG To: c.schroeter@emi-tec.hu
RWH DEBUG Cc:
RWH DEBUG Subject: Locker, smart und modern: PACK AND GO!
RWH DEBUG Date: Sunday, April 12, 2020, 11:07 UTC+2
RWH DEBUG Font face: Tahoma Font size: 13px Color: #000000
RWH DEBUG Composed Email Headers: <div id="rwhMsgHeader"><br /><hr 
id="rwhMsgHdrDivider" style="border:0;border-top:1px solid 
#B5C4DF;padding:0;margin:10px 0 5px 0;width:100%;"><div 
style="font-family:Tahoma !important; color:#000000 !important; 
font-size:13px !important;"><b>From:</b> JACK WOLFSKIN</div><div 
style="font-family:Tahoma !important; color:#000000 !important; 
font-size:13px !important;"><b>Sent:</b> Sunday, April 12, 2020, 11:07 
UTC+2</div><div style="font-family:Tahoma !important; color:#000000 
!important; font-size:13px !important;"><b>To:</b> 
c.schroeter@emi-tec.hu</div><div style="font-family:Tahoma !important; 
color:#000000 !important; font-size:13px !important;"><b>Subject:</b> 
Locker, smart und modern: PACK AND GO!</div><br /></div>
RWH DEBUG Signature settings: inserts above the quote
RWH DEBUG Is signature present: true
RWH DEBUG Thunderbird signature node: [object HTMLDivElement]
An error occurred, please report an issue to add-on author here - 
https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues Node was not found

It might be the last sentence with "Node was not found". I have the 
feeling, but can not say for sure, that the first occurrence of the 
problem was after changing the language to German and changing back 
didn't help. Next I will try is uninstalling the plugin and 
reinstalling. Maybe this helps. I'll  let you know.

With my best regards

Robert

------------------------------------------------------------------------
*From:* 2BeeOrNot
*Sent:* Saturday, April 11, 2020, 23:21 UTC+2
*To:* jeevatkm/ReplyWithHeaderMozilla 
<ReplyWithHeaderMozilla@noreply.github.com>
*Cc:* Koala66 <rkahl@live.de>, Mention <mention@noreply.github.com>
*Subject:* [jeevatkm/ReplyWithHeaderMozilla] No Signature on Forward TB 
68.7 (#97)

**Comment by Koala66** [comment]
Hello,

I uninstalled and reinstalled. I get the same result. For the Forward it 
does not use the settings of RWH but the build in of Thunderbird + it 
removes the signature. And replay is with English (from, sent, to, cc, 
subject) and forward is German (Betreff, Datum, von, an, etc.), and I 
got the following error log:


NS_NOINTERFACE: Component returned failure code: 0x80004002 
(NS_NOINTERFACE) [nsISupports.QueryInterface] stack-trace-collector.js:84
window.controllers/Controllers sollte nicht mehr verwendet werden. 
Verwenden Sie es nicht für die Browser-Erkennung. blank <about:blank>
RWH DEBUG Initializing ReplyWithHeader v2.2.1 (Thunderbird 68.7.0, 
Windows, 20200407160932)
RWH DEBUG Email content-type: HTML
RWH DEBUG Email compose type: Forward
RWH DEBUG Message URI: 
imap-message://R.Kahl@mail.businesmail.com/INBOX#8719584
RWH DEBUG Date format: Locale (en-US), Time format: 24-hour, Include 
short timezone info
RWH DEBUG From: Sandra Mai &lt;S.Mai@emi-tec.de&gt;
RWH DEBUG To: 'Robert Kahl' &lt;R.Kahl@emi-tec.de&gt;
RWH DEBUG Cc: Helmut Kahl &lt;h.kahl@emi-tec.de&gt;
RWH DEBUG Subject: [I] Aufträge Dispensen + Vakummmetallisierung HU 
pass_files
RWH DEBUG Date: Thursday, April 9, 2020, 14:48 UTC+2
RWH DEBUG Font face: Tahoma Font size: 13px Color: #000000
RWH DEBUG Composed Email Headers: <div id="rwhMsgHeader"><br /><hr 
id="rwhMsgHdrDivider" style="border:0;border-top:1px solid 
#B5C4DF;padding:0;margin:10px 0 5px 0;width:100%;"><div 
style="font-family:Tahoma !important; color:#000000 !important; 
font-size:13px !important;"><b>From:</b> Sandra Mai 
&lt;S.Mai@emi-tec.de&gt;</div><div style="font-family:Tahoma !important; 
color:#000000 !important; font-size:13px !important;"><b>Sent:</b> 
Thursday, April 9, 2020, 14:48 UTC+2</div><div style="font-family:Tahoma 
!important; color:#000000 !important; font-size:13px 
!important;"><b>To:</b> 'Robert Kahl' 
&lt;R.Kahl@emi-tec.de&gt;</div><div style="font-family:Tahoma 
!important; color:#000000 !important; font-size:13px 
!important;"><b>Cc:</b> Helmut Kahl &lt;h.kahl@emi-tec.de&gt;</div><div 
style="font-family:Tahoma !important; color:#000000 !important; 
font-size:13px !important;"><b>Subject:</b> [I] Aufträge Dispensen + 
Vakummmetallisierung HU pass_files</div><br /></div>
RWH DEBUG Signature settings: inserts above the quote
RWH DEBUG Is signature present: true
RWH DEBUG Thunderbird signature node: [object HTMLDivElement]
An error occurred, please report an issue to add-on author here - 
https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues Node was not found

It seems for the forward, it does not look for the language. Switching 
to English or German does not change anything, it's always German.

With my best regards

Robert


------------------------------------------------------------------------
*From:* 2BeeOrNot <notifications@github.com>
*Sent:* Saturday, April 11, 2020, 23:21 UTC+2
*To:* jeevatkm/ReplyWithHeaderMozilla 
<ReplyWithHeaderMozilla@noreply.github.com>
*Cc:* Koala66 <rkahl@live.de>, Mention <mention@noreply.github.com>
*Subject:* [jeevatkm/ReplyWithHeaderMozilla] No Signature on Forward TB 
68.7 (#97)

**Comment by jeevatkm** [comment]
@Koala66 Thanks for the logs, I will look into it.
