### ISSUE TITLE
Start the work on adding support for TB 78+

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeaderMozilla#99]
It seems TB has pushing add-on on to next level challenge - Migrating to **WebExtension** otherwise, it won't work.

![Screen Shot 2020-04-29 at 1 44 59 AM](https://user-images.githubusercontent.com/1175977/80577316-8581fe00-89bb-11ea-9a8a-17dab01beb34.png)

🤔 First I have to start learning WebExtension so that I can migrate 😆

**Comment by jeevatkm** [comment]
As I looking into it, it turns this is a complex task and requires a rewrite of the add-on. Not sure how much time its going to take.

**Comment by jeevatkm** [comment]
I have read so many documents and investigated a lot also reached out TB community with few questions.
* https://thunderbird.topicbox.com/groups/addons/T6f81f0bbb7b18952/anyone-know-equivalent-of-compose-window-init-in-mailextension
* https://thunderbird.topicbox.com/groups/addons/T5c58b355f11ff49e/how-to-apply-locales-message-in-options-ui-html
* https://thunderbird.topicbox.com/groups/addons/Tfd56507268abcbca/gmsgcompose-editor-equivalent-in-mailextension
* https://thunderbird.topicbox.com/groups/addons/Tfff28c989c836e21/how-to-access-tb-settings-prefs-values-in-mailextension

Need to decide the path, let's see!

**Comment by jeevatkm** [comment]
Thought to mention it here for RWH users. 

As it turns out, brand new RWH MailExtension development (complete rewrite is required for TB 78+) is happening on branch `tb-78-mail-extension`

**Comment by jeevatkm** [comment]
RWH MailExtension development is in-progress. 

Technically it's happening in two parts -
* One for the short term - just make it work with workarounds in TB 78 
* Another one for the long term - a complete rewrite from scratch to support TB 78+ roadmap. This part is very time consuming and lots of effort involved. - No ETA
  * Good thing, I will bring new feature also using the latest TB capabilities 😉 

I appreciate your patience, thanks.

----

I'm hoping I will have a beta version for TB 78 in the upcoming week.

**Comment by jeevatkm** [comment]
Dear RWH User -

I have prepared the RHW v2.3.0-beta for try out.
Download Link: https://bit.ly/2F0cQNg
Sha256: 882b3abca3dde68413084d9680351dcee0b44d4c64cef4184e486abd3da30b11

Can you please test and share feedback?

_**PS:** This short-term goal is to make RWH work in TB 78 after that I will start work brand new RWH v3.0.0 Mail extension._

**Comment by BackSpace54** [comment]
Hi Jeevatkm,
i will try RWH beta tonight (in a couple of hours - here UTC/GMT +2).
Feedback coming soon ;-)

**Comment by tidebre67** [comment]
Hey Jeeva, tks for beta version. Testing was positive. Could not see any problem in this test. Seems to work as in previous TB versions.

**Comment by m-i-k-e-y** [comment]
@jeevatkm 

Thanks for the beta version. It is working, although the headers are hard to read when the dark theme is used.

**Comment by chdh** [comment]
@jeevatkm Thank you very much. I was waiting for this. It works fine for me with TB 78.3.1.

**Comment by BackSpace54** [comment]
Works like a charm except for "Reply list" : no headers remplacement.
Don't remember if it works with v2.2.1

**Comment by jeevatkm** [comment]
@BackSpace54, @tidebre67, @m-i-k-e-y, @chdh  - Thanks for the testing and confirmation.

@BackSpace54 - RWH add-on only supports Reply, Reply to All, and Forward.

@m-i-k-e-y - I have not learned the new TB theme concepts yet. The RWH v2.3.0 is just to make it work in TB 78. I will have to figure out the theme when working on RWH v3.0.0 Mail Extension. 

----

I have received positive feedbacks here as well as on Disqus threads on the [RWH page](https://myjeeva.com/replywithheader-mozilla). I will start preparing for submitting RWH v2.3.0 to ATN.

**Comment by jeevatkm** [comment]
Just now, I have submitted RWH v2.3.0 to ATN for review.

**Comment by weksupport** [comment]
Thank you very much !

On this moment, no problems and it looks good !

Regards,

Werner



------------------------------------------------------------------------
*Van:* Jeevanandam M. [mailto:notifications@github.com]
*Datum:* maandag 5 oktober 2020 02:07
*Aan:* jeevatkm/ReplyWithHeaderMozilla 
<ReplyWithHeaderMozilla@noreply.github.com>
*Cc:* WEK <wek@weksupport.nl>, Manual <manual@noreply.github.com>
*Onderwerp:* [jeevatkm/ReplyWithHeaderMozilla] Start the work on adding 
support for TB 78+ (#99)

**Comment by jeevatkm** [comment]
@weksupport Thanks for testing and confirmation.

**Comment by jeevatkm** [comment]
RWH v2.3.0 has been released to ATN and the new development will be tracked under #103.

**Comment by spodermenpls** [comment]
@jeevatkm Is it to be expected that I can't access the "RWH preferences" with the new 2.3.0 build? The add-on does work now (thank you for your efforts!), but is using the English instead of the German locale for the headers, that I'd prefer. I see that there's a commit called "... preferences page started working", but I only can access the "Details" and "Permissions" in the add-on panel.
